- ext/openssl/ossl_pkey.c
[Bug-#10735](https://bugs.ruby-lang.org/issues/10735)
We have been using the bug fix in production for over 5 months now without any issue. We'd like to upgrade our Ruby to the latest mainline, but as this bug is still present we cannot.
Would it be possible to merge this fix in?
> Apply patch @viktorium to dispose of context after signing

- .travis.yml
some tests with libressl-2.3.1 fails. It should ignored on Travis CI.
> Allow failures with libressl-2.3.1.

- lib/openssl/pkey.rb
- test/test_pkey_dh.rb
- test/utils.rb
512-bit DH keys are severely weak and have been implicated in recent attacks:
https://weakdh.org/
> Remove 512-bit DH group

- lib/openssl/ssl.rb
RC4 has insecure biases and both clients and servers should [not](https://tools.ietf.org/html/rfc7465) be using it.
> Remove RC4 cipher

- ext/openssl/ossl.c
Show the return values of both PKey::RSA#public? and #private? for each
two .pem files. The current example is not technically incorrect, but
very confusing.
This is based on the reports by Rob Nichols and Brett Goulder.
[Bug #10115] [GH ruby/openssl#52]
> Improve 'Loading a key' section of the documentation

- NEWS
- ext/openssl/ossl_pkey.c
- test/test_pkey_dsa.rb
- test/test_pkey_ec.rb
- test/test_pkey_rsa.rb
PKey.read is a generic method to load an arbitrary PKey structure from a
PEM or DER encoded String. Each PKey classes's constructor also can load
from a String, but the behavior on error is different. While they raises
its own exception (are subclasses of PKey::PKeyError), PKey.read raises
ArguementError.
https://bugs.ruby-lang.org/issues/11774
> Make PKey.read raise PKey::PKeyError rather than ArgumentError

- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_pkey.h
- ext/openssl/ossl_ssl.c
- test/test_ssl.rb
OpenSSL checks if the PKey's public key matches with the certificate,
but does not check that the PKey contains the private components. As a
result, OpenSSL does a NULL dereference while doing SSL/TLS negotiation.
https://bugs.ruby-lang.org/issues/8673
> ssl: reject keys without private components [Bug #8673]

- NEWS
- ext/openssl/ossl.c
- ext/openssl/ossl.h
- ext/openssl/ossl_ssl.c
- ext/openssl/ossl_x509store.c
- lib/openssl/ssl.rb
- test/test_ssl.rb
If a client sets this to true and enables SNI with SSLSocket#hostname=,
the hostname verification on the server certificate is performed
automatically during the handshake using
OpenSSL::SSL.verify_certificate_identity().
Currently an user who wants to do the hostname verification needs to
call SSLSocket#post_connection_check explicitly after the TLS connection
is established.
This commit also enables the option in SSLContext::DEFAULT_PARAMS.
Applications using SSLContext#set_params may be affected by this.
[GH ruby/openssl#8]
> ssl: add verify_hostname option to SSLContext

- lib/openssl/ssl.rb
- test/test_ssl.rb
Don't set in SSLContext#set_params when built with OpenSSL 1.1.0 or
newer.
The list was added as a workaround to exclude known weak cipher suites
([Bug #9424]). In OpenSSL <= 1.0.2, the default list (DEFAULT) included
even cipher suites using MD5. Now, OpenSSL 1.1.0 has better DEFAULT. So
make SSLContext#set_params just use it.
Here is the diff between our current explicit list and DEFAULT of
OpenSSL 1.1.0-pre6 (with sorted):
~~~
$ list_ruby=$(openssl ciphers -v $(ruby -ropenssl -e'puts OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ciphers]') | sort)
$ list_default=$(openssl ciphers -v 'DEAFULT:!PSK:!SRP' | sort)
$ diff <(echo "$list_ruby") <(echo "$list_default")
7,12c7
< DHE-DSS-AES128-GCM-SHA256 TLSv1.2 Kx=DH       Au=DSS  Enc=AESGCM(128) Mac=AEAD
< DHE-DSS-AES128-SHA256   TLSv1.2 Kx=DH …
> ssl: conditionally set explicit cipher suite list

- .travis.yml
- History.md
- tool/ruby-openssl-docker/Dockerfile
- tool/ruby-openssl-docker/README.md
I'm thinking of dropping support for unmaintained versions of LibreSSL.
According to the support schedule described on libressl.org[1], a stable branch is maintained for 1 year after an OpenBSD release that ships with it is published. So, LibreSSL 2.2, which was the version on OpenBSD 5.8 released on 2015-08, is no longer supported officially.
Unlike OpenSSL, since there are no (at least I don't know) redisributions with extended support, I think it's completely safe to drop old versions.
@zzak @hsbt What do you think?
[1]: http://www.libressl.org/releases.html
> Drop support for LibreSSL < 2.3

- CONTRIBUTING.md
- Rakefile
- appveyor.yml
- tool/ruby-openssl-docker/init.sh
Follow up for #80. Seeing if Travis and AppVeyor are happy with this.
---
Parse the dependency gems from openssl.gemspec and install them. This is
extracted from tool/ruby-openssl-docker/init.sh.
.travis.yml, appveyor.yml and CONTRIBUTING.md are also updated to use
the new task.
> Add install_dependencies rake task that installs testing dependencies

- README.md
It's not immediately clear from the README exactly what this project is
> Add "for Ruby" to the README title

- ext/openssl/ossl_engine.c
Replace `A EngineError` with `An EngineError`.
cf. https://github.com/ruby/ruby/pull/1502
> Fix a typo in ossl_engine.c

- ext/openssl/ossl_asn1.c
- test/test_asn1.rb
encountered this error using a certificate that is accepted by other clients:
```
OpenSSL::X509::Certificate.new File.read ("openssl_test.crt")
TypeError: bad GENERALIZEDTIME format
```
this is from asn1parse:
```
147:d=2  hl=2 l=  30 cons:   SEQUENCE          
149:d=3  hl=2 l=  13 prim:    GENERALIZEDTIME   :201401010000Z
164:d=3  hl=2 l=  13 prim:    UTCTIME           :390512144609Z
```
> asn1: handle GENERALIZEDTIME without seconds

- ext/openssl/ossl_asn1.c
- test/test_asn1.rb
This change fixes the `ASN1::Constructive.each` implementation that was broken with commit 36bf7f403ebb6cefcaa1e7af9d8ec99e6b4bc1ed (see @tidoublemy's comment on that commit for code to reproduce the issue).
Included are two small tests to test for correct behavior of the `each` implementation and that an appropriate exception will be raised (instead of SIGSEGV'ing) when non-array data is specified in Ruby for the `value` attribute.
> Fix for ASN1::Constructive 'each' implementation

- ext/openssl/ossl.c
- ext/openssl/ossl_ssl.c
- test/test_ssl.rb
The 'certificate verify error' is one of the most common errors that can
be raised by OpenSSL::SSL::SSLSocket#connect. The certificate
verification may fail due to many different issues such as misconfigured
trusted certificate store or inaccurate system clock.
Unfortunately, since the detail is not put to the queue and is only
accessible through OpenSSL::SSL::SSLSocket#verify_result, it is
sometimes hard to figure out the real reason. Let's include a human
readable reason message in the exception message. Like this:
require "socket"
require "openssl"
ctx = OpenSSL::SSL::SSLContext.new
ctx.set_params(cert_store: OpenSSL::X509::Store.new)
ssl = OpenSSL::SSL::SSLSocket.new(Socket.tcp("ruby-lang.org", 443), ctx)
ssl.connect
↓
-:7:in `connect': SSL_connect returned=1 errno=0 state=error: …
> ssl: show reason of 'certificate verify error' in exception message

- README.md
Firstly, thank you for you're hard work.
I was browsing through the README and noticed that it's being documented that you can fetch master using git and bundler using:
gem 'openssl', github: 'ruby/openssl'
The `github` gem option in Bundler uses the `git://` protocol to fetch the repository and this protocol is unfortunately not secure. I have changed the documentation to instead use the `git` option using `https` as the protocol.
> Document using secure protocol to fetch git master

- lib/openssl/bn.rb
The comment "Add double dispatch to Integer" should not leak into the class documentation for Integer:
```
$ ri Integer
Integer < Numeric
(from ruby site)
------------------------------------------------------------------------------
[snip other stuff that doesn't belong here]
Add double dispatch to Integer
[snip]
Holds Integer values.  You cannot add a singleton method to an Integer. Any
attempt to add a singleton method to an Integer object will raise a TypeError.
```
See also https://docs.ruby-lang.org/en/2.4.0/Integer.html.
> Fix rdoc for core Integer class

- .travis.yml
- tool/ruby-openssl-docker/Dockerfile
Hello,
I updated Rubies to latest version in `tool/ruby-openssl-docker/Dockerfile`
I also added `ruby-head` as allow_failures.
I think testing with `ruby-head` is useful.
Because we can support the next version Ruby as faster.
You can see that some Rubygem packages that are bundled in Ruby, also are testing on `ruby-head`.
https://github.com/yuki24/did_you_mean/blob/master/.travis.yml
https://github.com/ruby/bigdecimal/blob/master/.travis.yml
My concern is currently this `openssl` is tested on Docker.
It is hard to test `ruby-head` on Docker.
Because we have to get HEAD of the Ruby trunk branch, and do `docker build` regularly to create the container image.
I added `ruby-head` to `.travis.yml` directly due to that reason.
I takes longer time to finish tests.
But `fast_finish: true` option …
> Update .travis.yml and Dockerfile

- ext/openssl/ossl.c
- test/test_fips.rb
`OpenSSL::OPENSSL_FIPS` causes confusion as the doc states it returns a boolean based on if FIPS is 'enabled' which isn't true. It is dependent on whether the openssl installed was built with FOM (fips object module). If it was then it will always returns true (even when `fips_mode = false`), thus it is more accurate to say FIPS-capable.
Adding `OpenSSL.fips_mode` to return whether or not fips_mode is currently set. This allows for better handling around fips mode.
> Add fips_mode_get to return fips_mode

- openssl.gemspec
RubyInstaller2 supports metadata tags for installation of dependent
MSYS2/MINGW libraries. The openssl gem requires the mingw-openssl
package to be installed on the system, which the gem installer takes
care about, when this tag is set.
The feature is documented here:
https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#msys2-library-dependency
This fixes issues like 
https://github.com/oneclick/rubyinstaller2/issues/54 and 
https://github.com/oneclick/rubyinstaller2/issues/53 .
> Add msys2 library dependency tag in gem metadata

- ext/openssl/ossl_ssl.c
That there is no immediately readable data in the SSL instance does not
imply it has to read more bytes from the underlying socket. Just call
SSL_read() and check the return value.
> ssl: remove useless call to rb_thread_wait_fd()

- test/test_ssl.rb
OpenSSL in Debian sid has recently disabled TLS < 1.2 by default, so in
order to test that TLS 1.1 works, we need to explicitly make our test
client accept it.
> test/test_ssl: explicitly accept TLS 1.1 in corresponding test

- ext/openssl/extconf.rb
- ext/openssl/ossl_ssl.c
- lib/openssl/ssl.rb
- test/test_ssl.rb
- test/utils.rb
Add methods that set the minimum and maximum supported protocol
versions for the SSL context. If the OpenSSL library supports, use
SSL_CTX_set_{min,max}_proto_version() that do the exact thing.
Otherwise, simulate by combining SSL_OP_NO_{SSL,TLS}v* flags.
The new methods are meant to replace the deprecated
SSLContext#ssl_version= that cannot support multiple protocol versions.
SSLContext::DEFAULT_PARAMS is also updated to use the new
SSLContext#min_version=.
> ssl: add SSLContext#min_version= and #max_version=

- ext/openssl/ossl_x509name.c
- test/test_x509name.rb
> Add X509::Name#to_utf8 and #inspect

- lib/openssl/x509.rb
- test/test_x509name.rb
Allow the attribute value to contain ',', just as the openssl utility's
parse_name() function does.
Fixes: https://github.com/ruby/openssl/issues/39
> x509name: update regexp in OpenSSL::X509::Name.parse

- ext/openssl/ossl_ssl.c
- test/test_pair.rb
Set the length of the buffer string to 0 first, and adjust to the size
successfully read by the SSL_read() call later. This is needed because
the buffer string may be provided by the caller.
> ssl: prevent SSLSocket#sysread* from leaking uninitialized data

- ext/openssl/ossl.c
Although it's not documented explicitly that the locking callbacks must
provide reentrant mutexes, it seems to be required.
Specifically, the session_remove_cb callback function of an SSL_CTX is
called in a critical section for CRYPTO_LOCK_SSL_CTX, which is shared
across the library. This leads, if the callback function calls another
OpenSSL function that will attempt to lock CRYPTO_LOCK_SSL_CTX, to
deadlock. SSL_CTX_free() is one example of such a function.
http://ci.rvm.jp/results/trunk@P895/64001
> ossl.c: make legacy locking callbacks reentrant

- ext/openssl/ossl_ssl.c
- test/test_ssl_session.rb
In OpenSSL < 1.1.0, the session_remove_cb callback is called inside the
global lock for CRYPTO_LOCK_SSL_CTX which is shared across the entire
process, not just for the specific SSL_CTX object. It is possible that
the callback releases GVL while the lock for CRYPTO_LOCK_SSL_CTX is
held, causing another thread calling an OpenSSL function that tries to
acquire the same lock stuck forever.
Add a note about the possible deadlock to the docs for
SSLContext#session_remove_cb=, and skip the relevant test cases unless
the OSSL_TEST_ALL environment variable is set to 1.
A deadlock due to this issue is observed:
http://ci.rvm.jp/results/trunk-test@frontier/104428
> test/test_ssl_session: skip tests for session_remove_cb

- ext/openssl/ossl_x509cert.c
- ext/openssl/ossl_x509revoked.c
- lib/openssl/x509.rb
- test/test_x509attr.rb
- test/test_x509cert.rb
- test/test_x509crl.rb
- test/test_x509ext.rb
- test/test_x509req.rb
This pull request adds:
- OpenSSL::X509::Extension#==
- OpenSSL::X509::Attribute#==
- OpenSSL::X509::Certificate#==
- OpenSSL::X509::CRL#==
- OpenSSL::X509::Revoked#==
- OpenSSL::X509::Revoked#to_der
- OpenSSL::X509::Request#==
#158 can be closed when this is merged.
cc: @mcr
> x509*: implement == 

- ext/openssl/ossl_ssl.c
- test/test_ssl.rb
Support for fallback SCSV [RFC 7507](https://tools.ietf.org/html/rfc7507).
Expected behaviour is to refuse connection if the client signals a protocol with
the fallback flag but the server supports a better one (downgrade attack detection).
> TLS Fallback Signaling Cipher Suite Value

- ext/openssl/openssl_missing.h
- ext/openssl/ossl.c
- ext/openssl/ossl.h
- ext/openssl/ossl_cipher.c
- ext/openssl/ossl_engine.c
- ext/openssl/ossl_ssl.c
- ext/openssl/ossl_x509cert.c
- ext/openssl/ossl_x509crl.c
The proposed changes remove the use of the OpenSSL 1.1.0 deprecated API.  Which fixes the following build errors that occur on Gentoo when building ruby 2.4.2 with openssl 1.1.0f built with no-deprecated:
compiling ossl.c
ossl.c: In function ‘Init_openssl’:
ossl.c:1014:5: warning: implicit declaration of function ‘OpenSSL_add_all_algorithms’; did you mean ‘OpenSSL_add_ssl_algorithms’? [-Wimplicit-function-declaration]
OpenSSL_add_all_algorithms();
^~~~~~~~~~~~~~~~~~~~~~~~~~
OpenSSL_add_ssl_algorithms
ossl.c:1015:5: warning: implicit declaration of function ‘ERR_load_crypto_strings’; did you mean ‘ERR_load_OCSP_strings’? [-Wimplicit-function-declaration]
ERR_load_crypto_strings();
^~~~~~~~~~~~~~~~~~~~~~~
ERR_load_OCSP_strings
ossl.c:1016:5: warning: implicit declaration of function …
> Fix build failure against OpenSSL 1.1 built with no-deprecated

- lib/openssl/buffering.rb
- test/test_pair.rb
As of Ruby 2.5, IO#write accepts multiple input strings and writes them
at once[1]. Follow that.
[1] https://bugs.ruby-lang.org/issues/9323
> buffering: let #write accept multiple arguments

- ext/openssl/ossl_ns_spki.c
- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_pkey.h
- ext/openssl/ossl_x509cert.c
- ext/openssl/ossl_x509crl.c
- ext/openssl/ossl_x509req.c
The pub_encode routine of an EVP_PKEY_ASN1_METHOD seems to assume the
parameters and public key component(s) to be set properly. Calling that,
for example, through X509_set_pubkey(), with an incomplete object may
cause segfault.
Use ossl_pkey_check_public_key() to check that. It doesn't look pretty,
but unfortunately there isn't a generic way to do that with the EVP API.
Something similar applies to the verify routine of an EVP_PKEY_METHOD.
Do the same check before calling *_verify().
Reference: http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/83688
Reference: https://bugs.ruby-lang.org/issues/14087
> [Bug #14087] x509cert, x509crl, x509req, ns_spki: check sanity of public key

- ext/openssl/ossl_pkey_rsa.c
- test/test_pkey_rsa.rb
Support Probabilistic Signature Scheme for RSA key signing.
[ky: the patch was originally submitted as GitHub Pull Request #76.
finish keyword arguments handling, update docs, and fix tests.]
This replaces #76. Merging this will close #75.
> [v2] Add RSA sign_pss() and verify_pss() methods

- ext/openssl/ossl_ssl.c
- test/envutil.rb
- test/test_ssl.rb
- test/utils.rb
Add a new method to add a certificate, a corresponding private key and
extra CA certificates at once.
This has two advantages over the existing {cert,key,extra_cert_chain}
attributes:
1. We can notice the problem with the certificate and/or the private
key. Since the existing attributes are just instance variables,
they aren't set to the SSL_CTX until #setup which usually happens
on the first connection.
2. For the same reason, existing attributes allowed only one
certificate for a context, even though OpenSSL itself is capable of
handling multiple certificates and selecting the most appropriate
one according to the cipher suite selected.
The existing attributes are now 'soft' deprecated and their RDoc
comments are updated to recommend #add_certificate.
> ssl: add SSLContext#add_certificate

- ext/openssl/ossl_kdf.c
- test/test_kdf.rb
OpenSSL 1.1.0 supports HKDF through the EVP API. Add OpenSSL::KDF.hkdf
as a wrapper around that.
Closes https://github.com/ruby/openssl/issues/172 if merged.
> kdf: add HKDF support

- ext/openssl/ossl_pkey_ec.c
- lib/openssl/pkey.rb
- test/test_pkey_ec.rb
Add a new method named PKey::EC#to_octet_string that returns the octet
string representation of the curve point. PKey::EC::Point#to_bn, which
have already existed and is similar except that an instance of
OpenSSL::BN is returned, is rewritten in Ruby.
PKey::EC::Point#initialize now takes String as the second argument in
the PKey::EC::Point.new(group, encoded_point) form.
Also, update the tests to use #to_octet_string instead of #to_bn for
better readability.
>  pkey/ec: add support for octet string encoding of EC point

- History.md
- ext/openssl/ossl_asn1.c
- ext/openssl/ossl_ssl.c
- openssl.gemspec
#177 is the only change since v2.1.0.beta2.
> Ruby/OpenSSL 2.1.0

- ext/openssl/ossl_pkcs7.c
- test/test_pkcs7.rb
The recipient's certificate is not mandatory for PKCS7_decrypt(). Make
it possible to call OpenSSL::PKCS7#decrypt with only the private key to
match the functionality with PKCS7_decrypt().
Reference: https://github.com/ruby/openssl/issues/182
> pkcs7: allow recipient's certificate to be omitted for PKCS7#decrypt

- lib/openssl/ssl.rb
- openssl.gemspec
- test/test_ssl.rb
IPv6 SAN-verification accommodates ["zero-compression"](https://tools.ietf.org/html/rfc5952#section-2.2). It also accommodates non-compressed addresses.
Previously the verification of IPv6 addresses would fail unless the address syntax matched a specific format (no zero-compression, no leading zeroes).
As an example, the IPv6 loopback address, if represented as `::1`, would not verify.  Nor would it verify if represented as `0000:0000:0000:0000:0000:0000:0000:0001`; however, both representations are valid, RFC-compliant representations.  The library would only accept a very specific representation (i.e.  `0:0:0:0:0:0:0:1`).
This commit addresses that shortcoming, and ensures that any valid IPv6 representation will correctly verify.
> Correctly verify abbreviated IPv6 SANs

- ext/openssl/ossl_cipher.c
- test/test_cipher.rb
EVP_BytesToKey() internally converts the iteration count given as an
"int" into an "unsigned int". Calling that with a negative integer will
result in a hang. This is surprising, so let's validate the value by
ourselves and raise ArgumentError as necessary.
The issue was reported by finixbit at https://hackerone.com/reports/304115 (not public yet)
> cipher: validate iterations argument for Cipher#pkcs5_keyivgen

- ext/openssl/extconf.rb
Our compat implementation of accessor functions that were introduced in
OpenSSL 1.1.0 conflicts with those from LibreSSL 2.7.0. Use the
HAVE_OPAQUE_OPENSSL code path when LibreSSL 2.7 or newer is detected.
Fix suggested by Joel Sing.
Fixes: https://github.com/ruby/openssl/issues/192
> extconf.rb: fix build with LibreSSL 2.7.0

- .travis.yml
- Dockerfile
- test/test_ssl.rb
- test/test_ssl_session.rb
- tool/ruby-openssl-docker/Dockerfile
- tool/ruby-openssl-docker/init.sh
> Test matrix update and additional test fixes for OpenSSL 1.1.1

- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_pkey.h
Key/parameter generation (OpenSSL::PKey::*.{new,generate}) immediately
aborts when it is done with GVL released (in other words, no block is
given) and the thread is interrupted (e.g., by a signal) during the
operation.
Have ossl_generate_cb_2() acquire GVL and call rb_thread_check_ints()
if needed to process the pending interrupt rather than abort the
operation completely by returning 0.
Reference: https://bugs.ruby-lang.org/issues/14882
> pkey: resume key generation after interrupt [Bug #14882]

- ext/openssl/ossl_asn1.c
While I'm guessing the `INT2NUM` calls all generate Fixnums and not Bignums,
it's unwise to rely on that.  Calling `rb_global_variable` directly after
assignment is the pattern used in `ossl.c`, and it's probably best to do
that here as well.
> Move rb_global_variable call to directly after assignment

- ext/openssl/ossl_x509name.c
- test/test_x509name.rb
X509_NAME_print_ex() behaves differently depending on the passed flags.
When XN_FLAG_COMPAT is specified, it returns either 1 on success or 0
on error. Otherwise, it returns the byte size written or -1 on error.
This means 0 return is not necessarily an error.
Also, X509_NAME_oneline() return value needs to be checked as it may
fail with a NULL return.
Fixes: https://github.com/ruby/openssl/issues/200
> x509name: fix handling of X509_NAME_{oneline,print_ex}() return value

- lib/openssl/buffering.rb
At the moment OpenSSL::Buffering#do_write allocates some additional
strings, and in my profiling writing 5MB of data allocates additional
7.7MB of strings.
This patch greatly reduces memory allocations, and now writing 5MB of
data allocates only additional 0.2MB of strings. This means that large
file uploads would effectively not allocate additional memory anymore.
Reference: https://bugs.ruby-lang.org/issues/14426
Reference: https://github.com/ruby/ruby/pull/1924
Cc: @janko-m
> Reduce memory allocation when writing to SSLSocket

- ext/openssl/ossl_cipher.c
The ciphers are defined inside the `OpenSSL::Cipher` namespace.
> Fix typo in docs

- test/test_pkey_ec.rb
LibreSSL 2.8.0+ does not support multiple elements in the first argument.
> Skip one assertion for OpenSSL::PKey::EC::Point#mul on LibreSSL

- ext/openssl/extconf.rb
- ext/openssl/openssl_missing.h
The OpenBSD ruby port has been using these for a while.  I think it would be best to  upstream these for better compatibility on other operating systems that use LibreSSL.
> Minor changes for better LibreSSL support

- ext/openssl/ossl_asn1.c
- test/test_asn1.rb
This makes it easier to compare OIDs.
> Define equality method for ASN1::ObjectId

- ext/openssl/extconf.rb
- ext/openssl/ossl_ssl.c
Enable post-handshake authentication with OpenSSL 1.1.1
Fixes #237
> Support client certificates with TLS 1.3

- ext/openssl/ossl_x509ext.c
- test/test_x509ext.rb
The `#value` method provides a weird stringification of the extension value that can't be parsed and isn't very useful. The new `#value_der` method provides the raw value, allowing users to decode the value and use it as needed.
For example, I'm wanting to use the Authority Key Identifier extension from a certificate. To do this currently, I do
```ruby
ext = cert.extensions.find { |c| c.oid == "authorityKeyIdentifier" }
if ext.nil?
raise "missing extension"
end
ext.value
#=> "keyid:E7:02:23:80:00:4F:D8:D7:BC:94:0B:D9:3F:74:39:49:32:3C:8A:79\n"
ext_asn1 = OpenSSL::ASN1.decode(ext.to_der)
unless ext_asn1.tag == OpenSSL::ASN1::SEQUENCE && [2, 3].include?(ext_asn1.value.length)
raise GitSigning::OCSPError, "invalid x.509 extension"
end
ext_value = ext_asn1.value.last
unless ext_value.tag == …
```
> Add OpenSSL::X509::Extension#value_der method

- tool/ruby-openssl-docker/Dockerfile
Right now we have to add some lines to change testing OpenSSL, libressl and Ruby versions.
This PR is to make us change the versions easily.
This PR does not change the actual logic. Just for refactoring.
```
root@056ea17fb644:/# ls /opt/openssl/
libressl-2.3  libressl-2.5  libressl-2.7   openssl-1.0.1  openssl-1.1.0
libressl-2.4  libressl-2.6  openssl-1.0.0  openssl-1.0.2  openssl-1.1.1
root@056ea17fb644:/# ls /opt/ruby/
ruby-2.3  ruby-2.4  ruby-2.5
```
I tested this PR's modification on my repository, and the result is success.
The Travis result: https://travis-ci.org/junaruga/openssl/builds/438665362
My pushed image: https://hub.docker.com/r/junaruga/ruby-openssl-docker/tags/
The testing modification on my repository: https://github.com/junaruga/openssl/commit/2bf6027e2bf046
> Refactor Dockerfile to modify installed OpenSSL/Ruby version easily.

- ext/openssl/ossl_bn.c
- test/test_bn.rb
Hi!
This PR is related to #248 .
* add nil-guard for 1st argument of `OpenSSL::BN.new` 
* fix doc
> OpenSSL::BN.new nil guard

- ext/openssl/ossl_pkey_rsa.c
- test/test_pkey_rsa.rb
The public exp not set would trigger this for #public_{en,de}crypt,
but OpenSSL::PKey::RSA#set does not allow setting a NULL public exp.
Fixes Ruby [Bug #15841]
> Fix segfaults in OpenSSL::PKey::RSA#private_{en,de}crypt when private exp not set

- ext/openssl/ossl_pkey_ec.c
- test/test_pkey_ec.rb
Hi, all.
I added support for `EC_POINT_add`.
I'll be the first to admit that I'm still learning my way around elliptic curve cryptography in general and OpenSSL in particular. This is also the first time I've ventured down to C with Ruby.
All of that's to say, I welcome your feedback.
> Add EC_POINT_add support

- ext/openssl/ossl.c
Althrough `OpenSSL::Cipher::Cipher` do exist, it's deprecated:
```ruby
cipher = OpenSSL::Cipher::Cipher.new 'AES-256-CBC'
```
> Fix minimal typo on documentation [skip ci]

- ext/openssl/ossl_cipher.c
- test/test_cipher.rb
This makes it obvious you have made a mistake if you call key= and
then encrypt or decrypt.  Calling encrypt or decrypt without an
argument automatically sets the key to NULL, in which case the
key_set ivar should be changed from false to true given if had
been set before calling encrypt or decrypt.
Fixes Ruby Bug 8720.
> Set key_set ivar to false if encrypt/decrypt called without key

- ext/openssl/ossl_x509name.c
- test/test_x509name.rb
Previously, OpenSSL::X509::Name#{cmp,<=>} would raise a TypeError if you
attempted to compare a Name object with another object of a different
type. Most Ruby classes instead return nil in this situation.
The old behavior resulted in some strange outcomes:
>> n1 = OpenSSL::X509::Name.new
>> 'abc' == n1
=> false
>> n1 == 'abc'
TypeError: wrong argument type String (expected OpenSSL/X509/NAME)
With the new behavior, cmp/<=> will return nil if the other object is
not an X509::Name instead of raising an error. This allows `==` to also
return false instead of raising an error for type mismatches.
New behavior:
>> n1 = OpenSSL::X509::Name.new
>> n1 == 'abc'
=> false
>> n1 <=> 'abc'
=> nil
> x509name: return nil for wrong type in Name#<=>

- test/test_x509name.rb
When running the test suite, these new warnings appears:
```
/src/test/test_x509name.rb:416: warning: ambiguous first argument; put parentheses or a space even after `-' operator
/src/test/test_x509name.rb:418: warning: ambiguous first argument; put parentheses or a space even after `-' operator
```
> Silence warning on spaceship tests

- ext/openssl/ossl_pkcs7.c
This method name is misleading, because it returns the name of the
signer's issuer, not the name of the signing certificate. It is
just an alias of issuer, which is more accurate.  The "name" method
is historical, it was replaced by the "issuer" method in 2005, and
since then has been alias for backwards compatibility.
There are no tests for the "name" method.
Fixes Ruby Bug 8178.
> Remove OpenSSL::PKCS7::SignerInfo#name

- lib/openssl/x509.rb
- test/test_x509cert.rb
- test/test_x509crl.rb
- test/utils.rb
I'm taking a stab at implementing some of the functionality discussed in https://github.com/ruby/openssl/pull/234#issuecomment-502712858. This stuff is kind of tedious to write, so I thought I'd open a PR that just adds helpers for two extensions to make sure we're on the same page about how this should work. Support for more extensions can be added in future PRs if this works out.
This PR adds a `#subject_key_identifier` method to the `Certificate` class that parses out the value of the `subjectKeyIdentifier` extension. This is fairly straightforward. This PR also adds a `#authority_key_identifier` method to the `Certificate` and `CRL` classes that parses out the value of the `authorityKeyIdentifier` extension. This extension has a number of possible fields and I decided that a `Hash` …
> Helpers for accessing AKI/SKI extensions of certs/crls

- ext/openssl/ossl_ssl.c
- test/test_ssl.rb
- test/utils.rb
Returns latest 'finished' messages sent and received.
> Adds support for the 'get_finished' and 'get_peer_finished' functions

- ext/openssl/ossl.c
- test/test_ossl.rb
Fixes https://bugs.ruby-lang.org/issues/10098 - at the 2019-02-07 developer meeting it was punted back to OpenSSL to implement. I went with @shyouhei's suggestion to mirror `String#casecmp?` naming.
One way or the other, I think having a function like this built in to the standard library instead of several application implementations is a good thing. E.g. [.NET Core](https://github.com/dotnet/corefx/pull/27103) has it too.
Some benchmarking on my Macbook Pro 15" 2018 shows this is also faster than Ruby implementations:
```
> BYTES=16 bundle exec benchmark.rb
Calculating -------------------------------------
Active Support    457.338k (± 0.8%) i/s -      2.311M in   5.053220s
Rack    569.963k (± 0.5%) i/s -      2.871M in   5.036927s
OpenSSL     11.822M (± 0.8%) i/s -     59.350M in …
```
> Add `OpenSSL.memcmp?` for constant time/timing safe comparison

- test/test_pkcs7.rb
The 2nd and 3rd arguments to write_smime are not really testable
without exposing additional OpenSSL constants to Ruby. Still, test
that write_smime works when passed 3 arguments.
Fixes Ruby Bug 8274.
> Add test for OpenSSL::PKCS7.{read,write}_smime

- ext/openssl/ossl_rand.c
- ext/openssl/ossl_ssl.c
- ext/openssl/ossl_x509store.c
Ruby 2.7 deprecates taint and it no longer has an effect.
The lack of taint support should not cause a problem in
previous Ruby versions.
> Remove taint support

- test/test_ssl.rb
Hi!
This PR is related to `test_finished_messages` method.
- fix flaky test
- `server_finished` would nil, if [assert_equal](https://github.com/ruby/openssl/blob/e7ed01b580a139ad0fb320ad5f29bbb40ef2ddc2/test/test_ssl.rb#L438L439) run before `server_finished` was assigned.
- clean `start_server` method `block` argument
- `start_server` method `block` argument requires an only [port](https://github.com/ruby/openssl/blob/e7ed01b580a139ad0fb320ad5f29bbb40ef2ddc2/test/utils.rb#L267).
You can reproduce the flaky bug, if you do the `git checkout e7ed01b` and insert `sleep` before [server_finished is assigned](https://github.com/ruby/openssl/blob/e7ed01b580a139ad0fb320ad5f29bbb40ef2ddc2/test/test_ssl.rb#L432).
> fix flaky test

- .github/workflows/workflow.yml
- ext/openssl/extconf.rb
- test/test_ssl.rb
Ubuntu 16.04 - Ruby 2.3, OpenSSL 1.1.1
Ubuntu 18.04 - Ruby 2.4, 2.5, 2.6, OpenSSL 1.1.1
macOS - 2.4, 2.5, 2.6, OpenSSL 1.0.2
Windows - Ruby 2.4, 2.5, 2.6, OpenSSL 1.0.2 & 1.1.1
Commits:
1. 'Add GitHub Actions- Ubuntu, macOS, Windows' - adds Actions, MinGW  jobs fully update MSYS2 toolchain and add correct OpenSSL files.
2. 'extconf.rb - update for new MSYS2, libssp' - current MSYS2 tools require using libssp.
3. 'OpenSSL::TestSSL#test_finished_messages - gracefully close client' - test would not pass on MinGW build using 1.1.1d.  Added two lines to close client
> Add GitHub actions

- ext/openssl/ossl.c
- lib/openssl.rb
- test/test_ossl.rb
Follow-up from the discussion over at https://github.com/ruby/openssl/pull/269#issuecomment-546559399 and https://github.com/ruby/openssl/commit/1ade643cbc01f3f7bd96e90bd8837df7ed491a09 where the Rails-like `secure_compare` naming was adopted. The debate around timing of hash functions made me realize why [Rails' default](https://github.com/rails/rails/pull/24510) of hashing the values to protect users from making mistakes is a good idea.
> Add hashed secure compare

- lib/openssl/x509.rb
- test/test_x509attr.rb
- test/test_x509cert.rb
- test/test_x509crl.rb
- test/test_x509ext.rb
- test/test_x509name.rb
- test/test_x509req.rb
This allows for example to use Rails' cache to store these objects. Without this patch you'd get errors like `TypeError (no _dump_data is defined for class OpenSSL::X509::Certificate)`.
Note that the X509::Revoked class doesn't need the newly introduced modules as the DER output of X509::CRL already includes these.
https://ruby-doc.org/core-2.6.5/Marshal.html
> Add Marshal support to X509 objects

- lib/openssl/x509.rb
- test/test_x509cert.rb
- test/utils.rb
Similar to https://github.com/ruby/openssl/pull/260
According to [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.2.1.13) a distribution point can contain a lot of things, but in practice I'm seeing only `fullName` URIs (`6`).
> Helper to retrieve CRL URIs from a certificate

- openssl.gemspec
ipaddr is a builtin class for ruby, that is occasionally merged. If the version isn't specified by the runtime dependency, then it will default to needing the latest gem rather than the version that ships with that version of ruby. That will lead to all kinds of potential dependency fails that are most likely unneeded since this gem already requires ruby > 2.3.0
> remove unneeded gem require for ipaddr

- .travis.yml
This PR comes from https://github.com/ruby/openssl/pull/230#issuecomment-548602977 .
Let's see how it works.
* I choose xenial, because "ruby/ruby" `.travis.yml` is using it.
* docker-compose is pre-installed.
* We can remove "group: edge", as it is added at
https://github.com/ruby/openssl/commit/7568c6e
> Update to dist: xenial.

- History.md
Going forward, History.md should be updated for all significant
new features, backwards compatibility issues, and performance
improvements.
> Add history for changes since 2.1.2

- History.md
- lib/openssl/x509.rb
- test/test_x509cert.rb
Hi!
This PR is in order to raise the appropriate exception.
if certificate extension ASN1 format is not appropriate, not `NoMethodError` but `ASN1Error` is raised.
> Raise ASN1::ASN1Error

- History.md
- ext/openssl/ossl_ocsp.c
- lib/openssl/x509.rb
- test/test_x509cert.rb
Hi!
This PR is similar to #260 and #275.
It adds `ca_issuer_uris` and `ocsp_uris` instance methods to `OpenSSL::X509::Certificate`.
> Helpers for accessing AIA extensions of certs

- History.md
- ext/openssl/ossl_pkey.c
- test/test_pkey_rsa.rb
Closes https://github.com/ruby/openssl/issues/294 by cherry-picking from https://github.com/ruby/openssl/pull/119 
The only line that needed changing to make it work on latest master was https://github.com/ruby/openssl/pull/119/files#diff-bae6e18b74ab1f890ac3e06a1aae16a2R614 to use `ossl_evp_get_cipherbyname ` as this was renamed in https://github.com/ruby/openssl/commit/679b6f490671439d1bc50ef4371d9fb3bbba0e29
> Export keys in PKCS8 format

- History.md
Wasn't entirely clear from https://github.com/ruby/openssl/pull/297 but it's noted here: https://github.com/ruby/openssl/pull/297/files#diff-bae6e18b74ab1f890ac3e06a1aae16a2R179-R181
and tested here: https://github.com/ruby/openssl/pull/297/files#diff-9837c7521b804179c365ed1071604f70R410-R429
> Clarify in history that PKCS8 reading is also supported

- ext/openssl/ossl_ocsp.c
- test/test_ocsp.rb
Hi!
This PR modifies the document about `CertificateId.new`.
When `CertificateId.new` is received only one argument,
`CertificateId.new` calls [ossl_to_der_if_possible](https://github.com/ruby/openssl/blob/6322ccbbf5671acc4cb1036f90b64e05e5ed3d28/ext/openssl/ossl_ocsp.c#L1511).
So, if it is the object that responds to the to_der method, it'll be okay.
For example, it is `OpenSSL::ASN1::ASN1Data` object.
This modifies
- the document about `CertificateId.new`
- the test about `CertificateId.new` by adding an assertion
> modify `CertificateId.new` doc

- ext/openssl/ossl.c
- ext/openssl/ossl_x509name.c
Addresses [issue 15882](https://bugs.ruby-lang.org/issues/15882) with [Zach Rowe's patch.](https://bugs.ruby-lang.org/attachments/7810)
The `#parse_openssl` method [expects a forward slash at the beginning of the argument](https://github.com/ruby/openssl/blob/master/lib/openssl/x509.rb#L302) if used as the delimiter.
```ruby
OpenSSL::X509::Name.parse_openssl('/CN=nobody/DC=example').to_a
OpenSSL::X509::Name.parse_openssl('CN=nobody/DC=example').to_a
```
> Prepend slashes to X509::Name.parse argument in examples

- .github/workflows/workflow.yml
See https://github.com/actions/checkout#usage - we only need one commit to do CI, not more.
> Use default fetch-depth of 1

- ext/openssl/ossl_ocsp.h
> Fix typo of `OpenSSL::OCSP` extern var

- ext/openssl/ossl_ssl.c
- test/test_ssl.rb
Hi!
This PR is related to #305.
This modifies `OpenSSL::SSL::SSLContext#add_certificate_chain_file` to accept the path to the private key.
This PR
- modifies `add_certificate_chain_file`
- adds the doc for `add_certificate_chain_file` 
- modifies testcase about `add_certificate_chain_file` 
This PR referenced `SSLContext#add_certificate`.
> Modify `SSLContext#add_certificate_chain_file`

- ext/openssl/ossl_ssl.c
Zero-size arrays not playing nicely with visual studio / mingw, see: https://github.com/ruby/ruby/pull/2693
Also see related discussion pertaining to using NULL pointer here: https://github.com/ruby/openssl/pull/315
> 'finished' messages: expand sizer array to 1-bytes

- History.md
- ext/openssl/ossl_ssl.c
- test/test_ssl.rb
Unfortunately, `add_certificate_chain_file` changes were broken with vs2015 to vs2019 environments. I revert all of the related commits for releasing 2.2.0.
> Revert add_certificate_chain_file changes

- openssl.gemspec
It failed to test with the ruby core repository.
> Drop to reference OpenSSL::VERSION on gemspec

- test/test_pkey_ec.rb
It fails with the RedHat platforms.
see https://rubyci.org/logs/rubyci.s3.amazonaws.com/rhel_zlinux/ruby-master/log/20200216T063303Z.fail.html.gz
> Guard for OpenSSL::PKey::EC::Group::Error with unsupported platforms

- test/test_ossl.rb
The test was too fragile.  Actually, it fails on one of our CIs
immediately after it was merged to ruby/ruby.
https://gist.github.com/ko1/7ea4a5826641f79e2f9e041d83e45dba#file-brlog-trunk_clang_40-20200216-101730-L532-L535
https://gist.github.com/ko1/1c657746092b871359d8bf9e0ad28921#file-brlog-trunk-test4-20200216-104518-L473-L476
* Two measurements, a-b and a-c, must be interative instead of
sequential; the execution time will be easily affected by disturbance
(say, cron job or some external process invoked during measurement)
* The comparison of the two results must be relative instead of
absolute; slow machine may take several tens of seconds for each
execution, and one delta second is too small.  The test cases of a, b,
and c are very extreme, so if the target method has a bug, the …
> Make OpenSSL::OSSL#test_memcmp_timing robust

- .travis.yml
Two jobs in Travis are duplicates of Actions jobs, and one is unlikely.
The below two jobs are running in Actions on all OS's
Ruby 2.3 and OpenSSL 1.0.2
Ruby 2.5 and OpenSSL 1.1.1
Ruby head and OpenSSL 1.0.2 - OpenSSL 1.0.2 is EOL, and the CI is running 1.0.2g, last release was 1.0.2u.
> .travis.yml - remove 2.3/1.0.2, 2.5/1.1.1, head/1.0.2

- lib/openssl/config.rb
- test/test_config.rb
OpenSSL 1.1.1 introduces a new '.include' directive. Update our config
parser to support that.
As mentioned in the referenced GitHub issue, we should use the OpenSSL
API instead of implementing the parsing logic ourselves, but it will
need backwards-incompatible changes which we can't backport to stable
versions. So continue to use the Ruby implementation for now.
Reference: https://github.com/ruby/openssl/issues/208
Cc: @voxik
> config: support .include directive

- test/openssl/test_ssl.rb
Run the test case only when the OpenSSL supports both TLS 1.1 and TLS
1.2. Note that the fallback SCSV mechanism is for TLS 1.2 or older and
not for 1.3.
Fixes: https://github.com/ruby/openssl/issues/336
> test/openssl/test_ssl: skip test_fallback_scsv if necessary

- ext/openssl/ossl_ts.c
- test/openssl/test_ts.rb
Stop the special treatment of invalid hashAlgorithm of the message
imprint. Those invalid values can only appear after the object is
instantiated, before the user sets an actual message digest algorithm.
OpenSSL::Timestamp::TokenInfo#algorithm already does the same.
Also, remove the test case "test_create_request" since it does not make
much sense. Those fields are to be set by the user after creation of
the object and checking the initial value is pointless.
Fixes: https://github.com/ruby/openssl/issues/335
> ts: simplify OpenSSL::Timestamp::Request#algorithm

- ext/openssl/ossl_ssl.c
We cannot use C99 features yet, as we still support Ruby 2.6 and older.
Fixes: debaca25604c ("Adds support for the 'get_finished' and 'get_peer_finished' functions", 2019-06-25)
> ssl: avoid declarations after statements

- ext/openssl/extconf.rb
- ext/openssl/ossl_engine.c
Revert two commits:
- ea49ccc82aa4 Add cloudhsm to extconf.rb
- 33ed3ba10424 Add cloudhsm to ossl_engine.c
OpenSSL::Engine.load is a binding for ENGINE_load_*() functions which
are provided by OpenSSL itself, so-called "static engines".
Since the AWS CloudHSM engine is a dynamic engine, which is provided as
a shared library, this change is not a correct solution for the issue.
Reference: https://github.com/ruby/openssl/issues/189
Reference: https://github.com/ruby/openssl/pull/190
> engine: revert OpenSSL::Engine.load changes for cloudhsm

- ext/openssl/extconf.rb
- ext/openssl/ossl_engine.c
engine: remove really outdated static engines
They no longer exists in OpenSSL 1.0.1, which is the oldest version
Ruby/OpenSSL currently compiles with.
Note that OpenSSL 1.0.2 and older is already in EOL state. The following
engines should also be removed when we completely drop support for those
versions as they were removed in OpenSSL 1.1.0.
- 4758cca
- aep
- atalla
- chil
- cswift
- nuron
- sureware
- ubsec
- gmp
- gost
---
engine: do not check for ENGINE_load_builtin_engines()
Remove dead code. The function, or a macro in OpenSSL 1.1.0 and newer,
always exists unless the whole engine code is disabled with
OPENSSL_NO_ENGINE.
---
engine: fix guards for 'dynamic' and 'cryptodev' engines
Those two engines exist as builtin engines even if static engines are
disabled with …
> engine: small cleanups on OpenSSL::Engine.load

- History.md
- lib/openssl/config.rb
- test/openssl/test_config.rb
OpenSSL::Config is currently implemented in Ruby, but we plan to revert
back to use OpenSSL API, just as it did before r28632 (in ruby_1_8;
r29048 in trunk). It's not clear what was the issue with Windows, but
the CONF library should work on Windows too.
Modifying a CONF object is not possible in OpenSSL API. Actually, it
was possible in previous versions of OpenSSL, but we used their
internal functions that are not exposed in shared libraries anymore.
Accordingly, OpenSSL::Config#add_value and #[]= have to be removed. As
a first step towards the change, let's deprecate those methods.
> config: deprecate OpenSSL::Config#add_value and #[]=

- lib/openssl.rb
- lib/openssl/version.rb
The OpenSSL::VERSION constant is now defined by lib/openssl/version.rb
instead of by the extension. Add missing require statement.
Fixes: 0cddb0b736c8 ("Simplify handling of version constant.", 2019-10-31)
Fixes: https://github.com/ruby/openssl/issues/347
> lib/openssl.rb: require openssl/version.rb

- openssl.gemspec
Use version.rb in gemspec so version string exists in one location.
I built the gem, and also built ruby with the same gemspec.  Both contained the version string as expected.
> Use version.rb in gemspec

- ext/openssl/ossl_ssl.c
- test/test_ssl.rb
When the verify_hostname option is enabled, the hostname verification is
done before calling verify_callback provided by the user.
The callback should be notified of the hostname verification failure.
OpenSSL::X509::StoreContext's error code must be set to an appropriate
value rather than OpenSSL::X509::V_OK.
If the constant X509_V_ERR_HOSTNAME_MISMATCH is available (OpenSSL >=
1.0.2), use it. Otherwise use the generic X509_V_ERR_CERT_REJECTED.
Fixes: https://github.com/ruby/openssl/issues/244
Fixes: 028e495734e9 ("ssl: add verify_hostname option to SSLContext", 2016-06-27)
> ssl: set verify error code in the case of verify_hostname failure

- test/openssl/test_ssl.rb
"test_close_after_socket_close" checks if ssl.close is no-op even after
the wrapped socket is closed.  The test itself is fair, but the other
endpoint that is reading the SSL connection may fail with SSLError:
"SSL_read: unexpected eof while reading" in some environments:
https://github.com/ruby/ruby/actions/runs/60085389 (MinGW)
https://rubyci.org/logs/rubyci.s3.amazonaws.com/android28-x86_64/ruby-master/log/20200321T034442Z.fail.html.gz
```
1) Failure:
OpenSSL::TestSSL#test_close_after_socket_close [D:/a/ruby/ruby/src/test/openssl/utils.rb:299]:
exceptions on 1 threads:
SSL_read: unexpected eof while reading
```
This changeset rescues and ignores the SSLError in the test.
Note: I've already committed this change into ruby/ruby to suppress the CI failures. …
> test/openssl/test_ssl.rb: ignore SSLError when the connection is closed

- .github/workflows/test.yml
1. Using correct MSYS compiler for Windows Ruby 2.3, previous CI used MSYS2.  It worked, but it wasn't ideal. `setup-ruby-pkgs` actually installs the DevKit for Ruby 2.2 & 2.3.
2. Ruby installation is done via a fork of `setup-ruby`.
Actions is relatively stable.  Going forward, `setup-ruby-pkgs` will be the custom action I support.
It is a generic package installation action that works with apt-get & brew, but especially handles the Windows build tools mess...
> Use setup-ruby-pkgs for Windows

- History.md
- lib/openssl/marshal.rb
- lib/openssl/pkey.rb
- lib/openssl/x509.rb
- test/openssl/test_pkey_dh.rb
- test/openssl/test_pkey_dsa.rb
- test/openssl/test_pkey_ec.rb
- test/openssl/test_pkey_rsa.rb
See https://github.com/ruby/openssl/pull/281#issuecomment-615958963
cc @mperham
> Add Marshal support to PKey objects

- ext/openssl/ossl_pkey.c
- test/openssl/test_pkey.rb
Implement OpenSSL::PKey::PKey#oid as a wrapper around EVP_PKEY_id().
This allows user code to check the type of a PKey object.
EVP_PKEY can have a pkey type for which we do not provide a dedicated
subclass. In other words, an EVP_PKEY that is not any of {RSA,DSA,DH,EC}
can exist. It is currently not possible to distinguish such a pkey.
Also, implement PKey#inspect to include the key type for convenience.
> pkey: add PKey#inspect and #oid

- CONTRIBUTING.md
- ext/openssl/ossl_cipher.c
- test/openssl/test_cipher.rb
As it is currently written the `Cipher` object can not be used in CCM mode with additional authenticate data. This is because per the OpenSSL documentation, when a Cipher is used in CCM mode the ciphertext, plaintext length must be specified to `EVP_CipherUpdate` as the `inl` parameter while both `in` and `out` are set to `NULL` (see the "CCM Mode" section of the OpenSSL docs here: https://www.openssl.org/docs/man1.1.1/man3/EVP_CipherUpdate.html). This PR changes the implementation of `#update` to allow the data parameter to be specified as an integer which is assumed to be the length of the ciphertext / plaintext for the update operation effectively fixing the limitation and allowing users to utilize the CCM mode.
Before the patch there would be an exception when trying to set …
> Allow specifying the data length for CCM mode

- .github/workflows/test.yml
- History.md
- ext/openssl/ossl.h
- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl.rb
Closes: https://github.com/ruby/openssl/issues/257
> Release 2.2.0

- ext/openssl/ossl.c
- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_pkey.h
- ext/openssl/ossl_pkey_dh.c
- ext/openssl/ossl_pkey_dsa.c
- ext/openssl/ossl_pkey_ec.c
- ext/openssl/ossl_pkey_rsa.c
- sample/echo_cli.rb
- sample/echo_svr.rb
- sample/gen_csr.rb
- sample/smime_read.rb
- sample/smime_write.rb
- test/openssl/test_pkey_dh.rb
- test/openssl/utils.rb
This is split from https://github.com/ruby/openssl/pull/119. This Pull Request mainly aims to reduce code duplication.
PKCS #8 formats support has been already merged by #297. I will create another Pull Request for generic pkey operations, including #generate_{key,params}, #derive, and one-shot #sign/#verify.
This probably should be merged after the v2.2.0 release.
> pkey: refactor PEM/DER serialization code

- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_pkey_dh.c
- ext/openssl/ossl_pkey_ec.c
- lib/openssl/pkey.rb
- test/openssl/test_pkey.rb
- test/openssl/test_pkey_dh.rb
- test/openssl/test_pkey_ec.rb
This is split from https://github.com/ruby/openssl/pull/119. This Pull Request implements more 'generic' operations using the EVP API.
PKCS #8 formats support has been already merged by #297. The code cleanup parts are in https://github.com/ruby/openssl/pull/328.
This probably should be merged after the v2.2.0 release.
This resolves https://github.com/ruby/openssl/issues/117 (X25519 support).
> pkey: add more support for 'generic' pkey types

- ext/openssl/ossl_pkey_ec.c
- test/openssl/test_pkey_ec.rb
Deprecate it for future removal. However, I do not expect any
application is affected by this.
The other form of calling it, PKey::EC::Point#mul(bn [, bn]) remains
untouched.
PKey::EC::Point#mul calls EC_POINTs_mul(3) when multiple BNs
are given as an array. LibreSSL 2.8.0 released on 2018-08 removed the
feature and OpenSSL 3.0 which is planned to be released in 2020 will
also deprecate the function as there is no real use-case.
Part of #369
> pkey/ec: deprecate OpenSSL::PKey::EC::Point#mul(ary, ary [, bn])

- ext/openssl/ossl.c
- ext/openssl/ossl_cipher.c
- test/openssl/test_cipher.rb
We ran into some Linux-based systems not accepting the upper case variant, see https://github.com/rubocop-hq/rubocop/pull/8262
> User lower case cipher names for maximum compatibility

- lib/openssl/hmac.rb
- test/openssl/test_hmac.rb
OpenSSL::HMAC implements the similar interface as ::Digest. Let's add
base64digest methods to OpenSSL::HMAC, too, for feature parity.
Originally suggested at: https://github.com/ruby/openssl/pull/371#discussion_r429680842
> hmac: implement base64digest methods

- ext/openssl/ossl.c
The socket is called `ssl_connection`, not `connection`
> Fix typo in documentation

- ext/openssl/ossl_pkey.c
* to emphasize `string` properly.
> [DOC] Fix RDoc markup

- lib/openssl/ssl.rb
- test/openssl/test_ssl.rb
**test/openssl/test_ssl: revise a test case for client_cert_cb**
The current test_client_auth_public_key test case checks that supplying
a PKey containing only public components through client_cert_cb will
cause handshake to fail. While this is a correct behavior as a whole,
the assertions are misleading in the sense that giving a public key is
causing the failure. Actually, the handshake fails because a client
certificate is not supplied at all, as a result of ArgumentError that is
silently ignored.
Rename the test case to test_client_cert_cb_ignore_error and simplify it
to clarify what it is testing.
---
**test/openssl/test_ssl: revise verify_mode test cases**
Add explicit test cases for the behaviors with different verify_mode.
If we made a bug in verify_mode, we would notice it by …
> ssl: initialize verify_mode and verify_hostname with default values

- ext/openssl/ossl_x509store.c
The certificate passed as the second argument was not properly free'd
in the error paths.
> x509store: fix memory leak in X509::StoreContext.new

- ext/openssl/ossl_ssl.c
Errno::EPROTOTYPE is not supposed to be raised by SSLSocket#write.
However, on macOS, send(2) which is called via SSL_write() can
occasionally return EPROTOTYPE. Retry SSL_write() so that we get a
proper error, just as ext/socket does.
Reference: https://bugs.ruby-lang.org/issues/14713
Closes: https://github.com/ruby/openssl/issues/227
This totally slipped my mind, but it seems this is still needed.
- master's test suite failing https://github.com/ruby/openssl/runs/975270914
> ssl: retry write on EPROTOTYPE on macOS

- ext/openssl/ossl_x509store.c
- test/openssl/test_x509store.rb
Update docs, tests, and improve error handling.
---
**x509store: update rdoc for X509::Store and X509::StoreContext**
Add more details about each method, and add reference to OpenSSL man
pages.
---
**x509store: let X509::Store#add_file raise TypeError if nil is given**
Undo special treatment of nil and simply pass the value to
StringValueCStr().
nil was never a valid argument for the method; OpenSSL::X509::StoreError
with an unhelpful error message "system lib" was raised in that case.
---
**x509store: emit warning if arguments are given to X509::Store.new**
Anything passed to OpenSSL::X509::Store.new was always ignored. Let's
emit an explicit warning to not confuse users.
---
**x509store: refactor X509::StoreContext#chain**
Use ossl_x509_sk2ary() to create an array of …
> Review OpenSSL::X509::Store

- ext/openssl/extconf.rb
- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl.rb
The underlying API SSL_CTX_set_tmp_ecdh_callback() was removed by
LibreSSL >= 2.6.1 and OpenSSL >= 1.1.0, in other words, it is not
supported by any non-EOL versions of OpenSSL.
The wrapper was initially implemented in Ruby 2.3 and has been
deprecated since Ruby/OpenSSL 2.0 (bundled with Ruby 2.4) with explicit
warning with rb_warn().
> ssl: remove SSL::SSLContext#tmp_ecdh_callback

- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl.rb
- test/openssl/test_ssl_session.rb
- test/openssl/test_ts.rb
- test/openssl/test_x509store.rb
This defines TLS1_3_VERSION when using LibreSSL 3.2.  LibreSSL 3.2
doesn't advertise this by default, even though it will use TLS 1.3
in both client and server modes.
Changes between LibreSSL 3.1 and 3.2 broke a few tests, Defining
TLS1_3_VERSION by itself fixes 1 test failure.  A few tests now
fail on LibreSSL 3.2 unless TLS 1.2 is set as the maximum version,
and this adjusts those tests.  The client CA test doesn't work in
LibreSSL 3.2, so I've marked that as pending.
With these changes, the tests pass on LibreSSL 3.2.
> Enhance TLS 1.3 support on LibreSSL 3.2

- ext/openssl/ossl_bn.c
Although the manpage says that BIGNUM functions return 0 on error,
OpenSSL versions before 1.0.2n and current LibreSSL versions may return
-1 instead.
Note that the implementation of OpenSSL::BN#mod_inverse is extracted
from BIGNUM_2c() macro as it didn't really share the same function
signature with others.
No tests added because such code paths are not reachable without BN_set_flags(). #417 covers it.
> bn: check -1 return from BIGNUM functions

- ext/openssl/ossl_pkey_ec.c
The form created an empty EC_GROUP object with the specified EC_METHOD.
However, the feature was unfinished and not useful in any way because
OpenSSL::PKey::EC::Group did not implement wrappers for necessary
functions to set actual parameters for the group, namely
EC_GROUP_set_curve() family.
EC_GROUP object creation with EC_METHOD explicitly specified is
deprecated in OpenSSL 3.0, as it was apparently not intended for use
outside OpenSSL.
It is still possible to create EC_GROUP, but without EC_METHOD
explicitly specified - OpenSSL chooses the appropriate EC_METHOD for
the curve type. The OpenSSL::PKey::EC::Group.new(<:GFp|:GF2m>, p, a, b)
form will continue to work.
This is part of #369 (OpenSSL 3.0 support).
> pkey/ec: remove OpenSSL::PKey::EC::Group.new(ec_method) form

- ext/openssl/ossl_pkcs7.c
- test/openssl/test_pkcs7.rb
ASN1_dup() will not copy the 'pkey' field of a PKCS7_SIGNER_INFO object
by design; it is a temporary field kept until the PKCS7 structure is
finalized. Let's bump reference counter of the pkey in the original
object and use it in the new object, too.
This commit also removes PKCS7#add_signer's routine to add the
content-type attribute as a signed attribute automatically. This
behavior was not documented or tested. This change should not break any
working user code since the method was completely useless without the
change above.
> pkcs7: keep private key when duplicating PKCS7_SIGNER_INFO

- ext/openssl/ossl_bn.c
- test/openssl/test_bn.rb
Provides an efficient way to guarantee positive values
Resolves #429 - missing chunk from prior PR
> Implement OpenSSL::BN#abs

- .github/workflows/test.yml
- ext/openssl/extconf.rb
- ext/openssl/openssl_missing.c
- ext/openssl/openssl_missing.h
- ext/openssl/ossl.c
- ext/openssl/ossl_ocsp.c
- ext/openssl/ossl_ssl.c
- ext/openssl/ossl_ts.c
- ext/openssl/ossl_x509.c
- test/openssl/test_asn1.rb
- test/openssl/test_ocsp.rb
- test/openssl/test_ssl.rb
OpenSSL 3.0 support (#369) will need us to add new version guards. To keep it maintainable, I would like to do some cleanup before that happens.
Nearly 4 years have passed since OpenSSL 1.0.1's EOL and I think we are good with dropping it now. FWIW, rubyci.org at the moment has one instance running OpenSSL 1.0.1 - `Ubuntu armv7l eabihf` which is Ubuntu 14.04 LTS.
The first commit updates code where we had explicit version guards. The following commits are to catch up with recent LibreSSL releases which merged features from OpenSSL.
---
**require OpenSSL >= 1.0.2 and LibreSSL >= 3.1**
Clean up old version guards in preparation for the upcoming OpenSSL 3.0
support.
OpenSSL 1.0.1 reached its EOL on 2016-12-31. However, we decided to keep
1.0.1 support as that time because many major Linux …
> require OpenSSL >= 1.0.2 and LibreSSL >= 3.1

- ext/openssl/ossl_pkey.c
- test/openssl/test_pkey_rsa.rb
Similarly to OpenSSL::PKey.generate_key and .generate_parameters, add
an optional parameter to OpenSSL::PKey::PKey#sign and #verify to specify
strings for EVP_PKEY_CTX_ctrl_str().
> pkey: allow setting algorithm-specific options in #sign and #verify

- ext/openssl/extconf.rb
- ext/openssl/openssl_missing.h
- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_pkey.h
- ext/openssl/ossl_pkey_dh.c
- ext/openssl/ossl_pkey_dsa.c
- ext/openssl/ossl_pkey_rsa.c
- lib/openssl/pkey.rb
- test/openssl/test_pkey_dh.rb
- test/openssl/test_pkey_dsa.rb
This pull request updates key/parameters generation methods of OpenSSL::PKey::{RSA,DSA,DH} (in other words, all but EC).
This is part of #369 (OpenSSL 3.0 support).
---
**pkey/dh: use high level EVP interface to generate parameters and keys**
Implement PKey::DH.new(size, gen), PKey::DH.generate(size, gen), and
PKey::DH#generate_key! using OpenSSL::PKey.generate_parameters and
.generate_key instead of the low level DH functions.
Note that the EVP interface can enforce additional restrictions - for
example, DH key shorter than 2048 bits is no longer supported by
default in OpenSSL 3.0. The test code is updated as such.
---
**pkey/rsa: use high level EVP interface to generate parameters and keys**
Implement PKey::RSA.new(size, exponent) and PKey::RSA.generate using
OpenSSL::PKey.generate_key …
> pkey: use high level EVP interface to generate parameters and keys

- lib/openssl/buffering.rb
- test/openssl/test_ssl.rb
- test/openssl/ut_eof.rb
Normal sockets respond to `getbyte`, so we should make SSLSocket respond
to `getbyte` as well.  This way we can substitute SSLSockets for regular
sockets.
> Add SSLSocket#getbyte

- ext/openssl/ossl_pkey.h
Remove the following methods, which have been marked as deprecated and
produced a warning since version 2.0, commit 7ea72f1f5084 ("adapt
OpenSSL::PKey to OpenSSL 1.1.0 opaque structs", 2016-06-05).
- OpenSSL::PKey::RSA#n=, #e=, #d=, #p=, #q=, #dmp1=, #dmq1=, #iqmp=
- OpenSSL::PKey::DSA#p=, #q=, #g=, #priv_key=, #pub_key=
- OpenSSL::PKey::DH#p=, #g=, #priv_key=, #pub_key=
These methods could only work with OpenSSL 1.0.2 or older, which is now
EOL.
> pkey: remove deprecated parameter setters

- ext/openssl/ossl_pkcs7.c
- ext/openssl/ossl_ssl_session.c
- ext/openssl/ossl_x509cert.c
- ext/openssl/ossl_x509crl.c
- ext/openssl/ossl_x509req.c
- test/openssl/test_x509cert.rb
Methods that take both PEM-encoding and DER-encoding have not been
consistent in the order in which encoding to attempt to parse.
A DER-encoding may contain a valid PEM block ("\n-----BEGIN ..-----" to
"-----END ...-----") embedded within it. Also, the PEM-encoding parser
allows arbitrary data around the PEM block and silently skips it. As a
result, attempting to parse data in DER-encoding as PEM-encoding first
can incorrectly finds the embedded PEM block instead.
This commit ensures that DER encoding will always be attempted before
PEM encoding. OpenSSL::X509::Certificate is one of the updated classes.
With this, the following will always be true:
obj == OpenSSL::X509::Certificate.new(obj.to_der)
obj == OpenSSL::X509::Certificate.new(obj.to_pem)
> x509, ssl, pkcs7: try to parse as DER-encoding first

- ext/openssl/ossl_bn.c
- test/openssl/test_bn.rb
Also, OpenSSL::BN::CONSTTIME is added.
OpenSSL itself had a feature that was vulnerable against a side-channel
attack. The OpenSSL authors determined that it was not a security issue,
and they have already fixed the issue by using BN_set_flags.
https://github.com/openssl/openssl/pull/13888
If a Ruby OpenSSL user was faced with a similar issue, they couldn't
prevent the issue because Ruby OpenSSL lacks a wrapper to BN_set_flags.
For the case, this change introduces the wrapper.
> Add OpenSSL::BN#set_flags and #get_flags

- .github/workflows/test.yml
- .gitignore
- Gemfile
- Rakefile
- openssl.gemspec
- test/openssl/envutil.rb
Back in 2016, we chose not to use Bundler in Ruby/OpenSSL development
because Bundler depended on openssl and could not be used for testing
openssl itself - "bundle exec rake test" would end up with loading two
different versions of openssl at the same time.
This was resolved long time ago and is not relevant anymore. We can now
safely use it for development dependency management and for Rake tasks
for simplicity.
> Use Bundler for dependency management and Rake gem tasks

- ext/openssl/ossl_kdf.c
I tried to use `OpenSSL::KDF.hkdf` to confirm RFC 5869, but I struggled there is no example code.
So I wrote an example.
> Add example to OpenSSL::KDF.hkdf method

- ext/openssl/ossl_ssl.c
* See https://bugs.ruby-lang.org/issues/18025
and https://github.com/ruby/ruby/pull/4629
> Use rb_block_call() instead of the deprecated rb_iterate() in OpenSSL

- ext/openssl/ossl.c
- ext/openssl/ossl.h
- ext/openssl/ossl_config.c
- ext/openssl/ossl_pkey_ec.c
- ext/openssl/ossl_ts.c
* Add `printf` format attribute to `ossl_raise`.
* Fix a format specifier in `config_load_bio`.
* Use `ASSUME` for the unreachable condition.
> Suppress printf format warnings

- .github/workflows/test.yml
- ext/openssl/extconf.rb
- ext/openssl/ossl_ssl.c
- test/test_ssl.rb
- test/test_ssl_session.rb
- test/utils.rb
Ruby/OpenSSL 2.1.x and 2.2.x will not support OpenSSL 3.0 API. Let's
make extconf.rb explicitly check the version number to be within the
acceptable range, since it will not compile anyway.
[Misc #18192] https://bugs.ruby-lang.org/issues/18192
> [2.1.x and 2.2.x] ext/openssl/extconf.rb: require OpenSSL version >= 1.0.1, < 3

- ext/openssl/ossl_ts.c
- test/openssl/test_ts.rb
prevent `ossl_ts_*_free()` from calling when `d2i_TS_*_bio()` failed.
See #405
> fix segv in Timestamp::{Request,Response,TokenInfo}.new

- ext/openssl/extconf.rb
- ext/openssl/ossl_ssl.c
- lib/openssl/ssl.rb
- test/openssl/test_ssl.rb
Provide a wrapper of SSL_set0_tmp_dh_pkey()/SSL_CTX_set_tmp_dh(), which
sets the DH parameters used for ephemeral DH key exchange.
SSLContext#tmp_dh_callback= already exists for this purpose, as a
wrapper around SSL_CTX_set_tmp_dh_callback(), but it is considered
obsolete and the OpenSSL API is deprecated for future removal. There is
no practical use case where an application needs to use different DH
parameters nowadays. This was originally introduced to support export
grade ciphers.
RDoc for #tmp_dh_callback= is updated to recommend the new #tmp_dh=.
Note that current versions of OpenSSL support automatic ECDHE curve
selection which is enabled by default. SSLContext#tmp_dh= should only be
necessary if you must allow ancient clients which don't support ECDHE.
This is part of #369.
> ssl: add SSLContext#tmp_dh= 

- ext/openssl/ossl_ssl.c
---
**ssl: create a temporary frozen string buffer when writing**
Since a blocking SSLSocket#syswrite call allows context switches while
waiting for the underlying socket to be ready, we must freeze the string
buffer to prevent other threads from modifying it.
Reference: https://github.com/ruby/openssl/issues/452
---
**ssl: temporary lock string buffer while reading**
Similarly to SSLSocket#syswrite, the blocking SSLSocket#sysread allows
context switches. We must prevent other threads from modifying the
string buffer.
We can use rb_str_locktmp() and rb_str_unlocktmp() to temporarily
prohibit modification of the string.
> ssl: prevent string buffers from being modified outside #sys{read,write}

- ext/openssl/ossl_pkey_ec.c
RSTRING_LENINT() checks the range of int and raises an exception as
necessary. OpenSSL::PKey::EC#dsa_verify_asn1 currently does not do this,
and giving a too big string to it can trigger a surprising behavior:
ec.dsa_verify_asn1(digest, signature)               #=> true
ec.dsa_verify_asn1(digest, signature + "x" * 2**32) #=> true
Reference: https://hackerone.com/reports/1246050
> pkey: use RSTRING_LENINT() instead of casting to int

- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl.rb
OpenSSL::SSL::SSLSocket allowed #read and #write to be called before an
SSL/TLS handshake is completed. They passed unencrypted data to the
underlying socket.
This behavior is very odd to have in this library. A verbose mode
warning "SSL session is not started yet" was emitted whenever this
happened. It also didn't behave well with OpenSSL::Buffering. Let's
just get rid of it.
Fixes: https://github.com/ruby/openssl/issues/9
> ssl: disallow reading/writing to unstarted SSL socket

- ext/openssl/ossl_pkey.c
- test/openssl/test_pkey_rsa.rb
OpenSSL 3.0 has rewritten routines to load pkeys (PEM_read_bio_* and
d2i_* functions) around the newly introduced OSSL_DECODER API.
This comes with a slight behavior change. They now decrypt and parse
each encountered PEM block, then check the kind of the block. This used
to be the reverse: they checked the PEM header to see the kind, and then
decrypted the content. This means that the password callback may now be
called repeatedly.
Let's use the OSSL_DECODER API directly on OpenSSL 3.0 so that the
return value from the password callback will be reused automatically.
This is part of #369 (Support OpenSSL 3.0). The patch was originally submitted in #399.
> pkey: use OSSL_DECODER to load encrypted PEM on OpenSSL 3.0

- ext/openssl/extconf.rb
- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_pkey.h
- ext/openssl/ossl_pkey_dh.c
- ext/openssl/ossl_pkey_dsa.c
- ext/openssl/ossl_pkey_ec.c
- ext/openssl/ossl_pkey_rsa.c
---
**pkey: do not check NULL argument in ossl_pkey_new()**
Passing NULL to ossl_pkey_new() makes no sense in the first place, and
in fact it is ensured not to be NULL in all cases.
---
**pkey: allocate EVP_PKEY on #initialize**
Allocate an EVP_PKEY when the content is ready: when #initialize
or #initialize_copy is called, rather than when a T_DATA is allocated.
This is more natural because the lower level API has been deprecated
and an EVP_PKEY is becoming the minimum unit of handling keys.
---
**pkey: use EVP_PKEY_dup() if available**
We can use it to implement OpenSSL::PKey::PKey#initialize_copy. This
should work on all key types, not just DH/DSA/EC/RSA types.
> pkey: allocate EVP_PKEY on #initialize

- Gemfile
- test/openssl/test_bn.rb
`OpenSSL::BN` has been made ractor-safed in 9e7cf9e , but there was no test.
To write tests, I picked up some cases from other cases. If it is not enough, please tell me.
> Add test cases to OpenSSL::BN using ractor

- test/openssl/test_ssl.rb
RFC 6066 states how some wildcard SAN entries MAY be handled, but
it does not say they MUST be handled.  LibreSSL 3.5.0 only handles
suffix wildcard SANs, not prefix wildcard SANs, or interior
wildcard SANs, so return early from the wildcard SAN tests on
LibreSSL 3.5.0.
Fixes #471
> Skip optional wildcard SAN tests on LibreSSL 3.5.0+

- ext/openssl/extconf.rb
- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl.rb
Added an instance method, 'ciphersuites=', to OpenSSL::SSL::SSLContext which allows users to set the TLSv1.3 cipher suites. Also, added unit tests for this method and improved the test coverage for the existing 'ciphers=' method.
Resolves #476
> Added 'ciphersuites=' method to allow setting of TLSv1.3 cipher suites along with some unit tests

- .github/workflows/test.yml
- ext/openssl/ossl.h
- ext/openssl/ossl_pkey.c
- test/openssl/test_ssl.rb
The openssl extension stopped building on LibreSSL 3.5. #499 attempts
to address this, but also includes some new features.  This pull request
is strictly limited to fixing bugs.
While trying to get tests to pass, I noticed OSSL_OPENSSL_PREREQ and
OSSL_LIBRESSL_PREREQ were broken due to operator precedence issues,
so this fixes those.
The remaining fix was a small test fix to allow tests to pass on LibreSSL 3.4,
due to a non-standard cipher name (changed to match OpenSSL in
LibreSSL 3.5).
> Make tests pass on LibreSSL 3.5 and 3.4

- ext/openssl/ossl_asn1.c
The + tag can only be used for single words. For multiple words the \<tt>
tag has to be used.
> Fix formatting in docs

- .github/workflows/test.yml
Simply added 3.1 and update `actions/checkout@v3`.
This PR has some of duplicated section with https://github.com/ruby/openssl/pull/491
> Update actions at 2022/3

- ext/openssl/ossl_ocsp.c
- test/openssl/test_ocsp.rb
SHA1 is not considered a safe cipher, and as such, it is by default disabled by a system-wide crypto policy on c9s and RHEL 9.
Calling the `sign` method of described classes on described OS raises an `InvalidDigest` exception.
This PR adjusts the behavior to use SHA256 by default instead of SHA1. Tests passed locally on this change.
An example of failing tests from the Ruby 3.1 test suite on such systems:
```
13) Error:
OpenSSL::TestOCSP#test_basic_response_der:
OpenSSL::OCSP::OCSPError: invalid digest
/builddir/build/BUILD/ruby-3.1.1/test/openssl/test_ocsp.rb:170:in `sign'
/builddir/build/BUILD/ruby-3.1.1/test/openssl/test_ocsp.rb:170:in `test_basic_response_der'
14) Error:
OpenSSL::TestOCSP#test_request_sign_verify:
OpenSSL::OCSP::OCSPError: invalid digest …
```
> Use SHA256 for OCSP BasicResponse and Request

- .github/workflows/test.yml
Due to recent changes in Actions, along with changes in ruby/setup-ruby, Ubuntu 22.04 Rubies and the Windows mswin Ruby are all built with OpenSSL 3.0.x.
Update CI to use them.
Closes #510
> [CI] add Ubuntu-22.04 and update mswin, all are OpenSSL 3

- ext/openssl/extconf.rb
When openssl is installed on a system with pkconfig files, it is impossible to compile and link against another version of the library.
This patch fixes this by ignoring pkconfig files when the option is given.
> ignore pkgconfig when openssl-dir option is specified

- test/openssl/test_ssl.rb
It does not raise an error when setting an invalid value to SSLContext ciphers on Ubuntu 18.04.
> Skip a new test when old OpenSSL

- .github/workflows/test.yml
Updates CI 'test-openssl' jobs to use current OpenSSL versions, `1.1.1l` to `1.1.1q`, and `3.0.1` to `3.0.5`.
> [CI] test.yml - test-openssls - use 1.1.1q, 3.0.5

- test/openssl/test_hmac.rb
See https://github.com/ruby/openssl/issues/369#issuecomment-1196306878 in issue 'Support OpenSSL 3.0'.
> [CI] TestHMAC#test_dup - remove 'pend' for OpenSSL 3

- ext/openssl/ossl_pkey.c
- test/openssl/test_pkey_rsa.rb
The following script causes SEGV:
```ruby
require "openssl"
OpenSSL::PKey::RSA.generate(2048).sign("SHA256", "", ["x"])
```
I confirmed that it seems that SEGV occurs if the last optional argument (normally a Hash) finally processed by `pkey_ctx_apply_options` is an Array or something like that.
Since a non-nil check has done at each method function (e.g. `ossl_pkey_sign`) prior to call `pkey_ctx_apply_options`, I added `Check_Type` at the beginning of that function. It might be more efficient to check much earlier.
> OpenSSL::PKey::PKey#sign etc. with wrong type option causes SEGV

- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl.rb
I need to generate shared ttls secrets from TLS sessions using this API.
Note this implementation is incomplete! as it does not allow using the context.
See the first commit how that could look. It did not work for me so I removed it.
Should I write a test for this?
Refs:
https://datatracker.ietf.org/doc/html/rfc5705
https://datatracker.ietf.org/doc/html/rfc8446#section-7.5
https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#exporter-labels
https://man.openbsd.org/SSL_export_keying_material.3
> implement SSLSocket#export_keying_material for doing RFC 5705 operations

- ext/openssl/extconf.rb
- ext/openssl/ossl_hmac.c
- test/openssl/test_hmac.rb
Current OpenSSL 3.0.x release has a regression with zero-length MAC
keys. While this issue should be fixed in a future release of OpenSSL,
we can use EVP_PKEY_new_raw_private_key() in place of the problematic
EVP_PKEY_new_mac_key() to avoid the issue. OpenSSL 3.0's man page
recommends using it regardless:
> EVP_PKEY_new_mac_key() works in the same way as
> EVP_PKEY_new_raw_private_key().  New applications should use
> EVP_PKEY_new_raw_private_key() instead.
Fixes https://github.com/ruby/openssl/issues/369#issuecomment-1224912710
> hmac: use EVP_PKEY_new_raw_private_key() if available

- ext/openssl/ossl_x509cert.c
- ext/openssl/ossl_x509crl.c
- ext/openssl/ossl_x509req.c
- ext/openssl/ossl_x509revoked.c
X509at_delete_attr() in OpenSSL master puts an error queue entry if
there is no attribute left to delete. We must either clear the error
queue, or try not to call it when the list is already empty.
> x509*: fix error queue leak in #extensions= and #attributes= methods

- lib/openssl/pkey.rb
- test/openssl/test_pkey_dsa.rb
DSA parameters generation via EVP_PKEY_paramgen() will not automatically
adjust the size of q value but uses 224 bits by default unless specified
explicitly. This behavior is different from the now-deprecated
DSA_generate_parameters_ex(), which PKey::DSA.generate used to call.
Fixes https://github.com/ruby/openssl/issues/483
Fixes: 1800a8d5ebaf ("pkey/dsa: use high level EVP interface to generate parameters and keys", 2020-05-17)
> pkey/dsa: let PKey::DSA.generate choose appropriate q size

- ext/openssl/ossl_pkey.c
- test/openssl/test_pkey_ec.rb
Scan through the input for a private key, then fallback to generic
decoder.
OpenSSL 3.0's OSSL_DECODER supports encoded key parameters. The PEM
header "-----BEGIN EC PARAMETERS-----" is used by one of such encoding
formats. While this is useful for OpenSSL::PKey::PKey, an edge case has
been discovered.
The openssl CLI command line "openssl ecparam -genkey" prints two PEM
blocks in a row, one for EC parameters and another for the private key.
Feeding the whole output into OSSL_DECODER results in only the first PEM
block, the key parameters, being decoded. Previously, ruby/openssl did
not support decoding key parameters and it would decode the private key
PEM block instead.
While the new behavior is technically correct, "openssl ecparam -genkey"
is so widely used that ruby/openssl does not …
> pkey: restore support for decoding "openssl ecparam -genkey" output

- ext/openssl/ossl_pkey_ec.c
- test/openssl/test_pkey_ec.rb
i2d_PUBKEY_bio() against an EC_KEY without the public key component
trggers a null dereference.
This is a regression introduced by commit 56f0d34d63fb ("pkey:
refactor #export/#to_pem and #to_der", 2017-06-14).
Fixes https://github.com/ruby/openssl/pull/527#issuecomment-1220504524
Fixes https://github.com/ruby/openssl/issues/369#issuecomment-1221554057
> pkey/ec: check existence of public key component before exporting

- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl.rb
This adds support to OpenSSL's `SSL_CTX_set_keylog_callback()`. This callback is invoked when TLS key material is generated or received, in order to allow applications to store this keying material for debugging purposes. It is invoked with an `SSLSocket` and a string containing the key material in the format used by NSS for its `SSLKEYLOGFILE` debugging output.
This PR adds the Ruby binding `keylog_cb` and the related tests.
Note that It is only compatible with OpenSSL >= 1.1.1. Even if LibreSSL implements `SSL_CTX_set_keylog_callback()` from v3.4.2, it does nothing (see  https://github.com/libressl-portable/openbsd/commit/648d39f0f035835d0653342d139883b9661e9cb6)
- Example
```ruby
context = OpenSSL::SSL::SSLContext.new
context.keylog_cb = proc do |ary|
_sock, line = ary …
```
> Add support to SSL_CTX_set_keylog_callback()

- lib/openssl/pkey.rb
Alternative to https://github.com/ruby/openssl/pull/546 for `maint-3.0` and `master` branch.
> Call out insecure PKCS #1 v1.5 default padding for RSA

- ext/openssl/ossl_bn.c
- test/openssl/test_bn.rb
This PR adds support for [`BN_mod_sqrt`](https://www.openssl.org/docs/manmaster/man3/BN_mod_sqrt.html) as `BN#mod_sqrt`.
> Add BN#mod_sqrt

- test/openssl/test_asn1.rb
- test/openssl/test_ns_spki.rb
- test/openssl/test_pkey_dsa.rb
- test/openssl/test_pkey_ec.rb
- test/openssl/test_pkey_rsa.rb
- test/openssl/test_x509cert.rb
- test/openssl/test_x509crl.rb
- test/openssl/test_x509req.rb
Systems such as RHEL 9 are moving away from SHA1
disabling it completely in default configuration.
This is a follow-up PR after https://github.com/ruby/openssl/pull/507. This PR has the goal of fixing the rest of the test failures [0] present on systems that disable SHA1, like RHEL 9 and Centos 9 stream, by default via a system-wide crypto policy.
Tests pass locally with these changes.
[0] https://gist.github.com/jackorp/bb6e3ff2cfd339f2f65afcdc5c9e4070
This supersedes https://github.com/ruby/openssl/pull/511
> Use SHA256 instead of SHA1 where needed in tests.

- ext/openssl/ossl_cipher.c
- test/openssl/test_cipher.rb
For some reasons, plaintext may be empty string.
ref https://www.rfc-editor.org/rfc/rfc9001.html#section-5.8
> Allow empty string to OpenSSL::Cipher#update

- ext/openssl/ossl.c
Adds back missing constant description on the documentation
Currently:
After fix:
> Fixes OPENSSL_LIBRARY_VERSION description on documentation

- Gemfile
And RDoc cannot install on GitHub Actions Ubuntu images for now, due to psych depending on libyaml-dev.
https://github.com/actions/runner-images/issues/6725
> Rake and test-unit are only for development

- ext/openssl/ossl_pkey_ec.c
Initially caught by @rhenium as a copy-paste mistake while reviewing #564, there are multiple `ossl_raise` calls which specify the wrong type.
I have another version of this commit here https://github.com/bannable/openssl/commit/7085fc410d463bd16f669d4aff561966ddb0e199 targeting 3.0/master if needed, since this does not apply entirely cleanly. Please let me know if you would like a separate PR for that.
> pkey/ec: fix multiple ossl_raise() calls using cEC_POINT instead of eEC_POINT

- ext/openssl/ossl_pkey_ec.c
Instead of returning true when EC_POINT_cmp or EC_GROUP_cmp error, raise instead.
> raise when EC_POINT_cmp or EC_GROUP_cmp error instead of returning true

- .github/workflows/test.yml
See [Ubuntu-latest workflows will use Ubuntu-22.04](https://github.com/actions/runner-images/issues/6399).
This branch should test against OpenSSL 1.1.1, but 'ubuntu-latest' will soon be Ubuntu-22.04, which uses OpenSSL 3.0.
Update Actions to use ubuntu-20.04, and update 'actions/checkout' from 'v2' to 'v3'
> maint-2.2 Actions - update workflow to use OpenSSL 1.1.1, actions/checkout@v3

- .github/workflows/test.yml
See [Ubuntu-latest workflows will use Ubuntu-22.04](https://github.com/actions/runner-images/issues/6399).
'master' should test against both OpenSSL 1.1.1 and OpenSSL 3.0.  Due to the above (changing 'ubuntu-latest' from 20.04 to 
22.04), the mix of CI done with each OpenSSL version changes.
For the standard CI done in the 'test' jobs, this now runs the same job matrix for OpenSSL 1.1.1 and OpenSSL 3.0.  Not sure if that's needed, especially with Ruby master?
> Actions - Use Ubuntu 20.04 for 1.1.1 CI, misc fixes

- .github/workflows/test.yml
- ext/openssl/ossl_ssl.c
- test/openssl/test_asn1.rb
- test/openssl/test_ssl.rb
Also, clean up old and unnecessary workarounds while we are at it.
Fixes #561
> Fix test failures with LibreSSL 3.6

- ext/openssl/ossl_ssl.c
- ext/openssl/ossl_ssl_session.c
- lib/openssl/ssl.rb
- test/openssl/test_pair.rb
- test/openssl/test_ssl.rb
- test/openssl/test_ssl_session.rb
This fixes a linkage error about `ossl_ssl_type` on platforms that do not have socket, like WASI.
Even before this patch, `OpenSSL::SSL::Socket.new` throws `NotImplementedError` under `OPENSSL_NO_SOCK` since https://github.com/ruby/ruby/commit/ee22fad45d394818690c4a7586d7bb576ba67c56 However, due to some new use of OpenSSL::SSL::Socket over the past few years, the build under `OPENSSL_NO_SOCK` had been broken.
This patch guards those new use of `OpenSSL::SSL::Socket` by `OPENSSL_NO_SOCK`.
* `SSLContext#servername_cb=`, which sets a callback taking a socket.
* `OpenSSL::Session`, which can accept a socket to create a new session.
> Undefine `OpenSSL::SSL` for no socket platforms

- test/openssl/test_engine.rb
- test/openssl/test_fips.rb
The problem:
some tests run test cases in a separate Ruby process, probably to not pollute the global namespace. To share test helpers a test file can be `require`d in this separate process. So there need additional efforts to prevent auto-launching etc.
I propose to not `require` a test file and to move such shared test helpers into a separate place.
Actually there are only 2 places where a test file is required
- `test_engine.rb`
- `test_fips.rb`
But only in one place it's really needed (to share test helpers).
Related PR: https://github.com/ruby/openssl/pull/589
> Do not require a test file in a separately run test case

- .github/workflows/test.yml
https://github.com/ruby/openssl/actions/runs/4190107682/jobs/7263178067
> Skip failing test with truffleruby and ubuntu-22.04

- openssl.gemspec
JRuby has its own implementation of the `openssl` library in jruby-openssl. The simplest way for us to allow users to set openssl as a gem dependency is to ship a stub gem that just depends on jruby-openssl. This patch adds that to the gemspec. Additional work may be required to fit this stub gem into the test and release process.
See #20 for more details.
> Stub gemspec for JRuby

- .github/workflows/test.yml
This PR is just to upgrade the tested OpenSSL version the latest ones.
https://www.openssl.org/source/
As Fedora 37+ already has the openssl 3.0.8, it's convenient if this repository has tests on the openssl version 3.0.8.
https://src.fedoraproject.org/rpms/openssl
> .github/workflows/test.yml: Update OpenSSL versions

- test/openssl/test_ssl.rb
A tentative measures for https://github.com/ruby/openssl/issues/606
> Relax error message for OpenSSL 3.1

- Gemfile
There is a case of the Ruby where the rdoc is not a default gem. That is Ruby RPM packages on Fedora Linux and maybe the downstream Linux distributions. The intention is to reduce the size of the main Ruby RPM package.
I appreciate if the ruby/openssl considers this case.
---
Right now the `rdoc` is used in the `Rakefile`. And the `bundle exec rake compile` raises an error with the Ruby RPM package. This pull-request fixes the error.
```
$ cat /etc/fedora-release 
Fedora release 37 (Thirty Seven)
$ which ruby
/bin/ruby
$ ruby -v
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
$ which gem
/bin/gem
$ which bundle
/bin/bundle
$ gem list rdoc
*** LOCAL GEMS ***
rdoc (6.4.0)
$ gem list | grep rdoc
rdoc (6.4.0) # <= It's not a default gem.
```
```
$ bundle install --standalone …
```
> Add rdoc as a development dependency.

- .github/workflows/test.yml
- ext/openssl/ossl.c
- test/openssl/fixtures/ssl/openssl_fips.cnf.tmpl
- test/openssl/test_fips.rb
This PR includes the 2 commits below.
* CI: Add OpenSSL FIPS mode case.
* Fix the fips_mode_get on OpenSSL 3.
The 1st commit is to add the latest stable OpenSSL version 3.0.8 FIPS mode to the CI. I was able to create the FIPS mode environment. That means you can create the environment in your local environment too!
The 2nd commit fixes the issue https://github.com/ruby/openssl/issues/605 related to the `OpenSSL.fips_mode` (`fips_mode_get`). The commit can be also a minimal fix to test the FIPS mode created by the 1st commit.
I referred to the following documents.
* https://github.com/openssl/openssl/blob/master/README-FIPS.md
* https://www.openssl.org/docs/manmaster/man7/fips_module.html
I prepared the OpenSSL config file to enable the FIPS mode: …
> Implement FIPS functions, adding OpenSSL FIPS mode case on CI.

- ext/openssl/ossl.c
This PR fixes #620. I wanted to add the cases on the CI. However I couldn't reproduce it on the CI. So, I checked the PR suppress the warnings on my local environment. Later I consider adding the CI cases to test the compiler warnings.
@botovq, thanks for the report. Could you check this PR on your environment, just in case? Thanks.
---
The commit c5b2bc1268bcb946ff2eb52904a85278a1dac12c made the warnings below in the case of OpenSSL 1.1 where the `OPENSSL_FIPS` macro is not defined.
```
$ ruby -v
ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-linux]
$ bundle install --standalone
$ bundle exec rake compile -- \
--with-openssl-dir=$HOME/.local/openssl-1.1.1t-debug \
--with-cflags="-Wundef"
mkdir -p tmp/x86_64-linux/openssl/3.2.1
cd tmp/x86_64-linux/openssl/3.2.1 …
```
> Fix warnings about the OPENSSL_FIPS macro in OpenSSL 1.1.

- test/openssl/test_hmac.rb
https://bugs.ruby-lang.org/issues/19386#note-11
> Revert "Skip OpenSSL::TestHMAC#test_dup when running with RHEL9"

- .github/workflows/test.yml
- tool/enable-mkmf-verbose
This PR is to print the compiling commands in the process of the `rake compile`, and enables us to detect the compiler warnings like the issue <https://github.com/ruby/openssl/issues/620> in a PR process. This is a workaround until a formal way to enable the verbose mode in runtime of Ruby will be implemented. You can see https://github.com/ruby/setup-ruby/issues/505#issuecomment-1555880562 for the proposal.
Here is the result on my forked repository.
Ubuntu Ruby 3.2
https://github.com/junaruga/openssl/actions/runs/5049251346/jobs/9058658930#step:6:81
> gcc -I. -I/opt/hostedtoolcache/Ruby/3.2.2/x64/include/ruby-3.2.0/x86_64-linux -I/opt/hostedtoolcache/Ruby/3.2.2/x64/include/ruby-3.2.0/ruby/backward -I/opt/hostedtoolcache/Ruby/3.2.2/x64/include/ruby-3.2.0 -I../../../../ext/openssl …
> CI: Enable the verbose mode in the mkmf.rb.

- ext/openssl/extconf.rb
- ext/openssl/ossl_ssl.c
See https://github.com/ruby/ruby/pull/6511 for more details.
cc @KJTsanaktsidis
> Remove usage of IO internals.

- ext/openssl/extconf.rb
According to the `mkmf.rb#init_mkmf`, there are command line options below.
* `--with-cflags` to set the `cflags`
* `--with-ldflags` to set the `ldflags`
For example the following command compiles with the specified flags. Note that
`MAKEFLAGS` is to print the compiler command lines.
```
$ MAKEFLAGS="V=1" \
bundle exec rake compile -- \
--with-cflags="-Wundef -Werror" \
--with-ldflags="-fstack-protector"
```
However, I couldn't find command line options to append the flags. And this
commit is to append the `cflags` and `ldflags` by the environment variables.
```
$ MAKEFLAGS="V=1" \
RUBY_OPENSSL_EXTCFLAGS="-Wundef -Werror" \
RUBY_OPENSSL_EXTLDFLAGS="-fstack-protector" \
bundle exec rake compile
```
The implementation was inspired by Nokogiri project. …
> Append flags from environment variables.

- Rakefile
This PR is for a preparation of the <https://github.com/ruby/openssl/issues/626>.
---
Print the Ruby and compiler info or the command itself before compiling.
The new task "debug_compiler" to print the Ruby and compiler version or,
compiler command itself for the debugging purpose. The task name is aligning
with the "debug" task that is to print the info in the Ruby OpenSSL binding for
the debugging purpose.
The compiler version info is useful when we hit the issues coming from the
newly updated compilers on the CI, and we find the cause.
> Print the Ruby and compiler info or the command itself before compiling.

- Rakefile
The `puts` method outputs the message to the `$stdout`, while the `sh` method outputs the message of the executed command to the `$stderr` by the `Rake.rake_output_message`.
https://github.com/ruby/rake/blob/v13.0.6/lib/rake/file_utils.rb#L51
This caused the message `Compiler: ...` not printed before the actual compiling task like the CI result below.
<https://github.com/ruby/openssl/actions/runs/5142797693/jobs/9256988158#step:6:141>.
> Rakefile: Print the message with `Rake.rake_output_message`.

- .github/workflows/test.yml
- ext/openssl/ossl_pkey.c
- test/openssl/test_pkey.rb
- test/openssl/utils.rb
This PR is to fix the following issue that is managed as one of the issues at <https://github.com/ruby/openssl/issues/603> on the FIPS mode. This PR is based on the PR <https://github.com/ruby/openssl/pull/608>. So, please consider reviewing and merging the #608 first. Then I can rebase this PR on the latest master branch.
```
$ openssl genrsa -out key.pem 4096
$ ruby -e "require 'openssl'; OpenSSL::PKey.read(File.read('key.pem'))"
-e:1:in `read': Could not parse PKey (OpenSSL::PKey::PKeyError)
from -e:1:in `<main>'
```
There are some commits on this PR. The first 3 commits are basically from the PR #603. Then the 4th commit is the main commit to fix this issue. The patch is the same with what I mentioned at <https://github.com/ruby/openssl/issues/603#issuecomment-1507152493>. The 4th and …
> Fix OpenSSL::PKey.read that cannot parse PKey in the FIPS mode.

- ext/openssl/ossl_bn.c
- ext/openssl/ossl_cipher.c
- ext/openssl/ossl_config.c
- ext/openssl/ossl_digest.c
- ext/openssl/ossl_engine.c
- ext/openssl/ossl_hmac.c
- ext/openssl/ossl_ns_spki.c
- ext/openssl/ossl_ocsp.c
- ext/openssl/ossl_pkcs12.c
- ext/openssl/ossl_pkcs7.c
- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_pkey_ec.c
- ext/openssl/ossl_ssl.c
- ext/openssl/ossl_ssl_session.c
- ext/openssl/ossl_ts.c
- ext/openssl/ossl_x509attr.c
- ext/openssl/ossl_x509cert.c
- ext/openssl/ossl_x509crl.c
- ext/openssl/ossl_x509ext.c
- ext/openssl/ossl_x509name.c
- ext/openssl/ossl_x509req.c
- ext/openssl/ossl_x509revoked.c
- ext/openssl/ossl_x509store.c
The vast majority have no reference so it's just a matter of setting the flags.
For the couple exception, they have very little references so it's easy.
> Implement Write Barrier for all OpenSSL types

- .github/workflows/test.yml
This PR is for refactoring. Sorry, I made this inconsistency for the YAML key names by the commit <https://github.com/ruby/openssl/commit/18b017218ca8022e26f2556f45232eaeb0890b24>. I want to fix this issue before modifying the GitHub Actions YAML file in addition.
---
GitHub Action YAML config file's key names are a style with the "foo-bar" (hyphen). This commit is to rename the key names with "foo_bar" (underscore) to "foo-bar" (hyphen) for consistency.
* Replaced "fips_enabled" with "fips-enabled".
* Replaced "append_configure" with "append-configure".
* Replaced "name_extra" with "name-extra".
> CI: Rename the key name "foo_bar" (underscore) to "foo-bar" (hyphen).

- .github/workflows/test.yml
- test/openssl/test_bn.rb
This PR has 2 commits. The first commit is to upgrade OpenSSL and LibreSSL versions to the latest versions. And the second commit is the cherry-pick from <https://github.com/ruby/openssl/pull/614> (thanks!). I am not sure that now is a good to upgrade the versions in the CI.
For the first commit, I have a question. How did you know the LibreSSL versions that are End of Life (EOL)? The latest release of the LibreSSL is for LibreSSL 3.8, 3.7 and 3.6. So, I assumed that Libre 3.5 is EOL now. Is that correct?
http://www.libressl.org/releases.html
> LibreSSL 3.8.0, 3.7.3, 3.6.3 (May 27th, 2023)
I added the URLs to check the OpenSSL and LibreSSL to the comments in the CI YAML file to make this regular task to upgrade the versions easy.
https://www.openssl.org/source/ …
> CI: Upgrade OpenSSL and LibreSSL versions.

- ext/openssl/extconf.rb
RUBY_OPENSSL_EXTCFLAGS and RUBY_OPENSSL_EXTLDFLAGS have been added for the primary purpose of custom warning flags for development and CI.
Since checking programs generated by mkmf may not be completely warning-free, we don't want to apply -Werror that may be supplied from these environment variables.
> extconf.rb: apply RUBY_OPENSSL_EXT{C,LD}FLAGS after checking features

- ext/openssl/ossl_pkey.c
clang generates a warning:
../../../../ext/openssl/ossl_pkey.c:326:22: error: implicit truncation from 'int' to a one-bit wide bit-field changes value from 1 to -1 [-Werror,-Wsingle-bit-bitfield-constant-conversion]
arg->interrupted = 1;
^ ~
1 error generated.
ref: https://github.com/ruby/openssl/pull/631
> pkey: use unsigned type for bit fields

- .github/workflows/test.yml
- ext/openssl/ossl.c
- ext/openssl/ossl.h
- openssl.gemspec
Ruby 2.6 has reached EOL on 2022-03. Requiring Ruby 2.7 allows us to use C99 syntax.
ref: https://github.com/ruby/openssl/pull/631
> Drop support for Ruby 2.6

- .github/workflows/test.yml
This PR fixes <https://github.com/ruby/openssl/issues/626>.
Add checks to make CI fail by compiler warnings in the `rake compile`.
If the `skip-warnings` (default: `false`, as an undefined variable is evaluated as `false` in the `if` syntax) is `true` in specific matrix cases, the cases skip the checks. If you want to skip new compiler warnings coming from external changes such as upgraded compiler or OpenSSL versions in the specific matrix cases, you can set the `skip-warnings: true` for the cases.
Note that this issue https://github.com/ruby/openssl/issues/628 was detected in the process of this work.
> CI: Check compiler warnings.

- .github/workflows/test.yml
This typo was found in the https://github.com/ruby/openssl/pull/635#issuecomment-1586548069 .
> CI: Fix a typo in the comment. [ci skip]

- .github/workflows/test.yml
- ext/openssl/ossl.c
- ext/openssl/ossl.h
- ext/openssl/ossl_provider.c
- ext/openssl/ossl_provider.h
- test/openssl/test_provider.rb
Hi! Thank you for great gem.
This PR fix #567 
Currently Ruby does not seem to have an API to load providers
To add a provider, you need to set the following file in OPENSSL_CONF
```ruby 
➜  ~ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
➜  ~ irb
irb(main):001:0> require 'openssl'
=> true
irb(main):002:0> OpenSSL::VERSION
=> "3.1.0"
irb(main):003:0> OpenSSL::OPENSSL_VERSION
=> "OpenSSL 3.1.0 14 Mar 2023"
irb(main):004:0> OpenSSL::OPENSSL_LIBRARY_VERSION
=> "OpenSSL 3.1.0 14 Mar 2023"
irb(main):005:0> OpenSSL::Cipher.new("RC4")
(irb):5:in `initialize': unsupported (OpenSSL::Cipher::CipherError)
from (irb):5:in `new'
from (irb):5:in `<main>'
~~~
➜  ~ cat .add_provider_conf
openssl_conf = openssl_init
[openssl_init]
providers = provider_sect
[provider_sect]
default = …
```
> add OpenSSL Provider support

- ext/openssl/extconf.rb
* See https://github.com/ruby/openssl/issues/650#issuecomment-1645699608
* Fixes #650.
> Always respect the openssl prefix chosen by truffle/openssl-prefix on TruffleRuby

- .github/workflows/test.yml
OpenSSL new versions were released for OpenSSL 3.1, 3.0 and 1.1.1.
https://www.openssl.org/source/
> CI: Upgrade OpenSSL versions.

- ext/openssl/extconf.rb
This pull-request fixes #617. At least it gives users an instruction in the case of `rake compile -- --with-openssl-dir=/path/to/openssl` below.
```
$ ls -l $HOME/.local/openssl-3.0.8-fips-debug-trace
total 20
drwxr-xr-x. 2 jaruga jaruga 4096 Apr 25 16:43 bin/
drwxr-xr-x. 3 jaruga jaruga 4096 Apr 25 16:43 include/
drwxr-xr-x. 5 jaruga jaruga 4096 Apr 25 16:43 lib64/
drwxr-xr-x. 4 jaruga jaruga 4096 Apr 25 16:45 share/
drwxr-xr-x. 5 jaruga jaruga 4096 May  2 18:24 ssl/
$ bundle exec rake compile -- --enable-debug --with-openssl-dir=$HOME/.local/openssl-3.0.8-fips-debug-trace
mkdir -p tmp/x86_64-linux/openssl/3.2.1
cd tmp/x86_64-linux/openssl/3.2.1
/usr/local/ruby-3.2.1/bin/ruby -I. -r.rake-compiler-siteconf.rb ../../../../ext/openssl/extconf.rb -- --enable-debug …
```
> Raise an error when the specified OpenSSL library directory doesn't exist.

- .github/workflows/test.yml
This PR is to add the cases to test Ruby OpenSSL binding (ruby/openssl) on OpenSSL master branch non-FIPS and FIPS cases.
My motivation for this PR is that we can immediately test Ruby OpenSSL binding with the OpenSSL where a PR to fix the issues related to our unit test was merged. There is a time lag until the next OpenSSL stable version including the fixes.
I reported one issue https://github.com/openssl/openssl/issues/21493 that caused some test failures in our unit test in FIPS case to the OpenSSL project (openssl/openssl), and the PR https://github.com/openssl/openssl/pull/21519#issuecomment-1665686153 fixing the issue was merged to the `master` branch (openssl-3.2.0-dev), (and `openssl-3.1` and `openssl-3.0` branches too) recently. Adding these CI cases by this PR, I can check the …
> CI: Add OpenSSL master branch head non-FIPS and FIPS cases.

- Rakefile
- ext/openssl/ossl.c
This PR is to enhance the feature of printing OpenSSL versions. This is useful when running tests conditionally depending on OpenSSL and LibreSSL versions. In my case, it was useful to fix pending tests in FIPS case. See my working branch [wip/fip-test-debug commits](
https://github.com/junaruga/openssl/commits/wip/fip-test-debug) to fix pending tests. The last 4 commits are mine. And the 3rd newest commit is the same with this PR's commit.
For the `OPENSSL_VERSION_NUMBER` format, the [OPENSSL_VERSION_NUMBER(3)](https://www.openssl.org/docs/manmaster/man3/OPENSSL_VERSION_NUMBER.html) documents were helpful for me. You can check each OpenSSL version's format by clicking the master, 3.1, 3.0, 1.1.1, 1.0.2 links. For adding the `OpenSSL::LIBRESSL_VERSION_NUMBER`, perhaps it is controversial. …
> Enhance printing OpenSSL versions.

- test/openssl/test_cipher.rb
- test/openssl/test_pkey.rb
- test/openssl/utils.rb
This PR is just for refactoring to use the common method `test/openssl/utils.rb#openssl?` instead of using the `OpenSSL::OPENSSL_VERSION_NUMBER` directly.
> Use openssl? instead of OpenSSL::OPENSSL_VERSION_NUMBER.

- test/openssl/test_pkey.rb
- test/openssl/utils.rb
This PR is to run the previously pended tests by the issues (https://github.com/openssl/openssl/issues/21493 and https://github.com/openssl/openssl/issues/20758) conditionally on OpenSSL versions including the fixes in FIPS case. The fixes were merged to the OpenSSL (openssl/openssl) master, openssl-3.1, and openssl-3.0 branches. See [this](https://github.com/openssl/openssl/pull/21519#issuecomment-1665686153). So, the coming stable versions should pass the tests.
> test/openssl/test_pkey.rb: Fix pending tests in FIPS case.

- ext/openssl/ossl.c
- test/openssl/test_config.rb
- test/openssl/test_ossl.rb
Error entries in the OpenSSL error queue may contain additional contextual information associated with the error, which can be helpful when debugging.
This "additional data" is currently only printed to stderr when OpenSSL.debug is enabled. Let's include this in the exception messages raised with ossl_raise(), too.
$ ruby -Ilib -ropenssl -e'OpenSSL.debug=true; OpenSSL::SSL::SSLContext.new.ecdh_curves="P-256:not-a-curve"'
-e:1: warning: error on stack: error:0A080106:SSL routines:gid_cb:passed invalid argument (group 'not-a-curve' cannot be set)
-e:1:in `ecdh_curves=': passed invalid argument (group 'not-a-curve' cannot be set) (OpenSSL::SSL::SSLError)
from -e:1:in `<main>'
> Include "additional data" message in OpenSSL errors

- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl.rb
When compiled with OpenSSL <= 1.1.1, OpenSSL::SSL::SSLContext#setup does not raise an exception on an error return from SSL_CTX_load_verify_locations(), but instead only prints a verbose-mode warning. This is not helpful since it very likely indicates an actual error, such as the specified file not being readable.
Also, OpenSSL's error queue is not correctly cleared:
$ ruby -w -ropenssl -e'OpenSSL.debug=true; ctx=OpenSSL::SSL::SSLContext.new; ctx.ca_file="bad-path"; ctx.setup; pp OpenSSL.errors'
-e:1: warning: can't set verify locations
["error:02001002:system library:fopen:No such file or directory",
"error:2006D080:BIO routines:BIO_new_file:no such file",
"error:0B084002:x509 certificate routines:X509_load_cert_crl_file: system lib"]
The behavior is currently different when compiled …
> ssl: raise SSLError if loading ca_file or ca_path fails

- ext/openssl/ossl.c
- ext/openssl/ossl_kdf.c
- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_pkey_dh.c
- ext/openssl/ossl_pkey_dsa.c
- ext/openssl/ossl_pkey_ec.c
- ext/openssl/ossl_pkey_rsa.c
Describe the behavior of OpenSSL::PKey::{DH,DSA,EC,RSA}#to_pem more clearly. Also, suggest the use of OpenSSL::PKey::PKey#private_to_pem and #public_to_pem when possible.
> [DOC] enhance RDoc for exporting pkeys

- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl.rb
Enrich SSLError's message with the low-level certificate verification result, even if SSL_get_error() returns SSL_ERROR_SYSCALL. This is currently done on SSL_ERROR_SSL only.
According to the man page of SSL_get_error(), SSL_ERROR_SYSCALL may be returned for "other errors, check the error queue for details". This apparently means we have to treat SSL_ERROR_SYSCALL, if errno is not set, as equivalent to SSL_ERROR_SSL.
Fixes: https://github.com/ruby/openssl/issues/606
> ssl: adjust "certificate verify failed" error on SSL_ERROR_SYSCALL

- ext/openssl/ossl.c
This PR improves and fixes typo created by the PR https://github.com/ruby/openssl/pull/662. Sorry! I checked the generated rdoc on local.
Note that here is the actual man content.
```
$ man -M /home/jaruga/.local/libressl-6650dce/share/man/ 3 LIBRESSL_VERSION_NUMBER
...
DESCRIPTION
OPENSSL_VERSION_NUMBER and LIBRESSL_VERSION_NUMBER are numeric release version
identifiers.  The first two digits contain the major release number, the third and
fourth digits the minor release number, and the fifth and sixth digits the fix re‐
lease number.  For OpenSSL, the seventh and eight digits contain the patch release
number and the final digit is 0 for development, 1 to e for betas 1 to 14, or f
for release.  For LibreSSL, OPENSSL_VERSION_NUMBER is always 0x020000000, and
LIBRESSL_VERSION_NUMBER always …
```
> Fix LIBRESSL_VERSION_NUMBER document mistake.

- .github/workflows/test.yml
- Rakefile
I would like to add FIPS information to the `rake debug`. It is convenient to check if Ruby OpenSSL binding is running with the OpenSSL with a proper FIPS configuration properly. I need to install many OpenSSL versions or specific commit versions with the FIPS configuration file to debug or fix a FIPS related issue.
---
Add FIPS information (FIPS enabled, and providers) to the `rake debug` task, and run the `rake debug` in FIPS case to check if OpenSSL is running in FIPS.
> Rakefile: Print FIPS information in the `rake debug`.

- .github/workflows/test.yml
According to the <https://github.com/openssl/openssl/discussions/21797>, the terminology "FIPS mode" should be used in the context of the latest OpenSSL any more. Replacing "FIPS mode" with "FIPS module" is recommended.
> CI: Replace "mode" in "FIPS mode" with "module".

- ext/openssl/ossl_pkey.c
- test/openssl/test_pkey.rb
- test/openssl/utils.rb
This PR has 3 commits.
The 1st commit is to remove the pending method pend_on_openssl_issue_21493. The 2nd commit is the same with this PR https://github.com/ruby/openssl/pull/668. I will rebase this PR after the PR #668 is merged. It's needed by the 3rd commit. And the 3rd commit is a workaround for the issue https://github.com/openssl/openssl/pull/21519, in the cases of the affected OpenSSL release versions.
I was thinking about my previous PR https://github.com/ruby/openssl/pull/664 to pend the related tests. And failing `OpenSSL::PKey.read(der_encoded_string)` with selection 0 is quite basic use case, and the issue may happen in other test files too. So, I thought a workaround is better than pending tests. Note the commit https://github.com/openssl/openssl/commit/2acb0d363c0032b5b97c4f …
> ossl_pkey.c: Workaround: Decode with non-zero selections.

- test/openssl/test_pkey_ec.rb
Check that OpenSSL::PKey::EC.builtin_curves returns an array in the expected format.
Similarly to OpenSSL::Cipher.ciphers, OpenSSL::PKey::EC.builtin_curves returns a list of known named curves rather than actually usable ones.
https://github.com/ruby/openssl/issues/671 found that the list may include unapproved (and thus unusable) curves when the FIPS module is loaded.
> test/openssl/test_pkey_ec.rb: refactor tests for EC.builtin_curves

- lib/openssl/buffering.rb
Prefer ``slice!`` for ``Buffering#consume_rbuff`` and safe navigation with ``ord`` for ``Buffering#getbyte``, similar to ``each_byte``.
> Refactor Buffering consume_rbuff and getbyte methods

- lib/openssl/ssl.rb
- test/openssl/envutil.rb
- test/openssl/test_digest.rb
- test/openssl/test_ns_spki.rb
- test/openssl/test_pkcs12.rb
- test/openssl/test_pkey_dsa.rb
- test/openssl/test_pkey_ec.rb
- test/openssl/test_pkey_rsa.rb
- test/openssl/test_ssl_session.rb
String#unpack1 avoids the intermediate array created by String#unpack for single elements, while also making a call to Array#first/[0] unnecessary.
> Prefer String#unpack1

- lib/openssl/ssl.rb
In TLS 1.2 or before, if DH group parameters for DHE are not supplied with SSLContext#tmp_dh= or #tmp_dh_callback=, we currently use the self-generated parameters added in commit bb3399a61c03 ("support 2048 bit length DH-key", 2016-01-15) as the fallback.
While there is no known weakness in the current parameters, it would be a good idea to switch to pre-defined, more well audited parameters.
This also allows the fallback to work in the FIPS mode.
The PEM encoding was derived with:
print OpenSSL::PKey.read(OpenSSL::ASN1::Sequence([OpenSSL::ASN1::Integer((<<-END).split.join.to_i(16)), OpenSSL::ASN1::Integer(2)]).to_der).to_pem
FFFFFFFF FFFFFFFF ADF85458 A2BB4A9A AFDC5620 273D3CF1
D8B9C583 CE2D3695 A9E13641 146433FB CC939DCE 249B3EF9
7D2FE363 630C75D8 F681B202 AEC4617A D3DF1ED5 D5FD6561 …
> ssl: use ffdhe2048 from RFC 7919 as the default DH group parameters

- ext/openssl/ossl_ocsp.c
`port` should be called on the `ocsp_uri` URI instead of the `ocsp` String.
> Fix OCSP documentation

- .github/workflows/test.yml
- ext/openssl/extconf.rb
- ext/openssl/ossl.c
- test/openssl/test_engine.rb
- test/openssl/test_fips.rb
- test/openssl/test_provider.rb
- test/openssl/utils.rb
Remove the OSSL_DEBUG flag and OpenSSL.mem_check_start which is only compiled when the flag is given. They are meant purely for development of Ruby/OpenSSL.
OpenSSL.mem_check_start helped us find memory leak bugs in past, but it is no longer working with the recent OpenSSL versions. Let's just remove it now.
> Remove OSSL_DEBUG compile-time option

- .github/workflows/test.yml
- Rakefile
- test/openssl/test_fips.rb
- test/openssl/test_pkey.rb
- test/openssl/test_pkey_ec.rb
- test/openssl/utils.rb
This PR fixes https://github.com/ruby/openssl/issues/671 fixing the `test_ECPrivateKey_encrypted` test in `test/openssl/test_pkey_ec.rb` in FIPS case, adding the test file to the CI.
The PR has 2 commits.
The 1st commit is a rework of `test_ed25519` in the `test/openssl/test_pkey.rb` in OpenSSL 3.1 and later versions FIPS case. The commit is to prepare the 2nd commit. I want to test it with asserting rather than pending. Because I think that raising the `OpenSSL::PKey::PKeyError` in the FIPS case is the expected behavior rather than pending status. I want to show that we are intentional for the raised error and error message.
The 2nd commit is the main commit to fix the `test/openssl/test_pkey_ec.rb` on the same way that is applied to the 1st commit by testing the FIPS case by asserting. …
> Fix test_pkey_ec.rb on FIPS.

- History.md
- README.md
- lib/openssl/version.rb
- openssl.gemspec
Changelog is written and version number is bumped. README is also updated while we're at it.
I want someone to review the content and also the language.
> Release 3.2.0

- test/openssl/test_x509ext.rb
Where `assert_match` converts string matcher argument to regexp first with escaping, `assert_include` does the same thing simpler.
> Exact checks with `assert_include`

- .github/workflows/test.yml
OpenSSL 3.2.0 is available now.
https://www.openssl.org/blog/blog/2023/11/23/OpenSSL32/
> CI: Add OpenSSL 3.2.0.

- History.md
When opening the `History.md` on VIM. A part of the text is unintentionally shown as italic below. We need to escape the markdown syntax `*` for italic.
You can see the `*` is escaped in the modified [`History.md`](https://github.com/junaruga/ruby-openssl/blob/wip/doc-escape-markdown-syntax/History.md#bug-fixes-6) on my forked repository.
> History.md: Escape Markdown syntax Italic "*". [ci skip]

- CONTRIBUTING.md
- README.md
I find the Markdown's reference-style links are helpful for a better readability when seeing the text file directly by an editor, or when referring to one link from multiple parts. And I see the reference-style links are used in some parts, but not in some other parts. So, I used the reference-style links for all the parts in `README.md` and `CONTRIBUTING.md`.
In the `README.md`, the references are written in the end of the each session. In the `CONTRIBUTING.md`, the references are written in the end of the file. So, I followed the existing style for each file.
I also checked all the links availability as a result, I changed the link of the `[DeveloperHowTo]` and removed the unused `[History.md]`.
My idea of the references is the link item names in the reference area at the end of the …
> Use Markdown reference-style links in documents. [ci skip]

- .github/workflows/test.yml
This PR is a workaround to pass the following failing tests addressed on #711. So, this PR technically fixes #711. The issue is that OpenSSL couldn't find the `lib\ossl-modules\legacy.dll`. The https://github.com/openssl/openssl/issues/19368 was helpful to understand teh issue and find the solution.
---
This commit is a workaround to avoid the following test failures by loading legacy provider.
```
2) Error: test_openssl_legacy_provider(OpenSSL::TestProvider): OpenSSL::Provider::ProviderError: Failed to load legacy provider: (null) (name=legacy)
D:/a/ruby-openssl/ruby-openssl/test/openssl/test_provider.rb:62:in `load'
D:/a/ruby-openssl/ruby-openssl/test/openssl/test_provider.rb:62:in `<main>'
D:/a/ruby-openssl/ruby-openssl/test/openssl/test_provider.rb:61:in `with_openssl' …
```
> Windows Ruby 3.3: Workaround: Set OPENSSL_MODULES to find providers.

- .github/workflows/test.yml
* Added the upstream rubyinstaller2 issue link as a comment. The issue is that the legacy provider (legacy.dll) not loaded in Windows MSYS2 OpenSSL 3 environment.
* Polished the text on the comment.
> CI: Added the rubyinstaller2 issue link that legacy provider is not loaded.

- lib/openssl/buffering.rb
- lib/openssl/ssl.rb
- test/openssl/test_pair.rb
Generic code that assumes the `Socket` interface will fail if it tries to use `wait` or `wait_readable` or `close_on_exec` family of methods. Can we add these?
> Add more methods to `SocketForwarder`.

- lib/openssl/ssl.rb
Both Red Hat and Debian-like systems configure the minimum TLS version to be 1.2 by default, but allow users to change this via configs.
On Red Hat and derivatives this happens via [crypto-policies](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening), which in writes settings in /etc/crypto-policies/back-ends/opensslcnf.config.  Most notably, it sets TLS.MinProtocol there. For Debian there's MinProtocol in /etc/ssl/openssl.cnf. Both default to TLSv1.2, which is considered a secure default.
In constrast, the SSLContext has a hard coded `OpenSSL::SSL::TLS1_VERSION` for `min_version`. TLS 1.0 and 1.1 are considered insecure. By always setting this in the default parameters, the …
> Only set min_version on OpenSSL < 1.1.0

- ext/openssl/extconf.rb
- ext/openssl/ossl_ssl.c
- lib/openssl/ssl.rb
- test/openssl/test_ssl.rb
(I expect this to fail on older Rubies until I add detection of `rb_eIOTimeoutError`).
> Add support for IO#timeout.

- test/openssl/test_ocsp.rb
Fixes: https://github.com/ruby/openssl/issues/695
> test/openssl/test_ocsp.rb: fix flaky test

- test/openssl/test_provider.rb
Tests of legacy provider failed with recent update of FreeBSD
https://rubyci.s3.amazonaws.com/freebsd13/ruby-master/log/20240207T023002Z.fail.html.gz
I make to skip them at `ruby/ruby` repo. please let me know if you have any idea about that.
Thanks ❤️
> omit tests related legacy provider

- .github/workflows/test.yml
- test/openssl/test_provider.rb
This PR is to omit (skip) tests requiring the legacy provider if it is not loadable. The issue was found by another PR https://github.com/ruby/openssl/pull/718.
---
In some cases, the legacy provider is not installed intentionally. So, we omit a test requiring the legacy provider if the legacy provider is not loadable.
In the test_openssl_provider_names test, we use base provider instead of legacy provider, because we would expect the base provider is always loadable in OpenSSL 3 for now.
You can see the list of the standard providers below.
https://wiki.openssl.org/index.php/OpenSSL_3.0#Providers
---
This PR has 2 commits. The 1st commit is to add the no-legacy case to the CI. I chose OpenSSL head branch for the no-legacy case. Because we can notice soon if the specification around the …
> test_provider.rb: Make a legacy provider test optional.

- ext/openssl/extconf.rb
* This reverts commit ca738e7e13570e88eaa9892cbb3dffb330320706 / https://github.com/ruby/openssl/pull/653.
* No longer needed since https://github.com/oracle/truffleruby/issues/3170 was fixed.
The fix is only in truffleruby-head, not yet in a release.
However, it seems truffleruby release is only used on ubuntu-22.04 in CI, where it works fine because anyway OpenSSL is picked: https://github.com/eregon/openssl/actions/runs/7060198654/job/19219283155#step:9:34
So it seems fine to merge this now and no need to wait for the 24.0 release.
> Revert openssl dir workaround on TruffleRuby

- lib/openssl/buffering.rb
Adjust the buffer write function to clear the buffer once, rather than piece by piece.  This avoids a case where a large write (in our case, around 70mbytes) will consume 100% of CPU.  This takes a webrick GET request via SSL from around 200kbyts/sec and consuming 100% of a core, to line speed on gigabit ethernet and 6% cpu utlization.
(The reason was that removing the head of the buffer was a full copy every single write block, which turned out to be 16k for us, hence every 16k copying the 77meg of data that went in the front of it).
Passes tests, and has been tested on our systems with chef-zero
> Fix regression in do_write(s) causing significant performance issues when using large (>10meg) writes

- ext/openssl/ossl_kdf.c
- ext/openssl/ossl_ns_spki.c
- test/openssl/test_ssl.rb
https://github.com/ruby/ruby/pull/10391
> Use www.rfc-editor.org for RFC text.

- test/openssl/test_x509req.rb
> Only CSR version 1 (encoded as 0) is allowed by PKIX standards

- lib/openssl/ssl.rb
- test/openssl/test_ssl.rb
Introduce `SSLSocket#close_read` and `SSLSocket#close_write` + relevant test.
`#close_read` is a no-op and exists to match the expected interface of `IO`.
`#close_write` uses `#stop` which in testing appears to do what we want.
Fixes <https://github.com/ruby/openssl/issues/609>.
> Introduce basic support for `close_read` and `close_write`.

- .github/workflows/test.yml
The issue https://github.com/oneclick/rubyinstaller2/issues/365 was fixed with the 3.2.4 and 3.3.1 releases.
> CI: Remove workaround for Ruby-3.2 and 3.3 on Windows

- ext/openssl/ossl_cipher.c
- ext/openssl/ossl_digest.c
- test/openssl/test_digest.rb
This returns the long names of digests. Similar to `OpenSSL::Cipher.ciphers` (I took most of the implementation from it)
Maybe the only confusing thing is that `Digest#name` returns the short name, `Cipher#name` does have a little disclaimer in the docs it might not be the same as given to the constructor.
> Add OpenSSL::Digest.digests to get a list of available digests

- .github/workflows/test.yml
- ext/openssl/ossl_pkey.c
- test/openssl/test_asn1.rb
- test/openssl/test_ssl.rb
- test/openssl/test_x509req.rb
Let's make GitHub Actions happy before making a patch release.
> Backport test fixes to 3.0

- ext/openssl/ossl_cipher.c
- test/openssl/test_cipher.rb
OpenSSL::Cipher#update currently allocates the output buffer with size (input data length)+(the block size of the cipher). This is insufficient for the id-aes{128,192,256}-wrap-pad (AES keywrap with padding) ciphers. They have a block size of 8 bytes, but the output may be 15 bytes larger than the input.
Use (input data length)+EVP_MAX_BLOCK_LENGTH (== 32) as the output buffer size, instead. OpenSSL doesn't provide a way to tell the maximum required buffer size for arbitrary ciphers, but this is large enough for all algorithms implemented in current versions of OpenSSL.
Fixes: https://bugs.ruby-lang.org/issues/20236
> cipher: fix buffer overflow in Cipher#update

- ext/openssl/ossl_pkcs7.c
- test/openssl/test_pkcs7.rb
This replaces https://github.com/ruby/openssl/pull/690.
- Based on https://github.com/ruby/openssl/pull/690 by @jeremyevans,
- rebased on top of maint-3.0,
- applied the diff https://github.com/ruby/openssl/pull/690#issuecomment-2016531030 by @pkuzco,
- corrected the exception type (`.read_smime` raises `OpenSSL::PKCS7::PKCS7Error` while `.new` raises `ArgumentError` -- which doesn't seem intentional, but that is a separate issue)
> Handle missing content in PKCS7

- ext/openssl/ossl_asn1.c
i2d_ASN1_TYPE() is not expected to fail, but the return value should be checked.
> asn1: check error return from i2d_ASN1_TYPE()

- ext/openssl/ossl_ssl.c
- test/openssl/test_pair.rb
To be consistent with regular Ruby IOs:
```ruby
r, _ = IO.pipe
buf = "garbage".b
r.read_nonblock(10, buf, exception: false) # => :wait_readable
p buf # => "garbage"
```
Ref: https://github.com/redis-rb/redis-client/commit/98b8944460a11f8508217bda71cfc10cb2190d4d
> read: don't clear buffer when nothing can be read

- ext/openssl/ossl_pkcs7.c
- ext/openssl/ossl_ts.c
- test/openssl/test_pkcs7.rb
- test/openssl/test_ts.rb
I added these while trying to debug why my timestamp usage was failing, figured someone else might find them useful as well
> Add to_text for PKCS7 and Timestamp::Response

- .github/workflows/test.yml
I saw this [comment](https://github.com/ruby/openssl/pull/756#issuecomment-2100177620), which referred to [failing tests](https://github.com/ruby/openssl/actions/runs/8999647687) on Windows for Ruby 3.0 thru 3.2.
I'm not exactly sure what the issue is, as it involves setup-ruby updating Bundler without updating RubyGems, which is done to some Windows Rubies due to a lack of a bash `bin/bundle` file.
Also, at present, two items:
1. CI is using Bundler with a Gemfile, but it's not using `bundle exec`. This works, as Bundler defaults to installing gems such that one doesn't need `bundle exec`.
2. Because of the above, every CI job is downloading and installing the gems, although `setup-ruby` can cache them.
This PR removes the `bundle install` step, and uses `setup-ruby`'s  `bundler-cache` …
> [CI] test.yml - use `bundle exec`, use setup-ruby bundler-cache, fixes Windows issue

- .github/workflows/test.yml
OpenSSL announced that they're changing how they handle releases in this blog post: https://openssl.org/blog/blog/2024/04/30/releases-distribution-changes/
The tl;dr is that:
* ftp.openssl.org is being shut down (even for HTTP access)
* The releases at openssl.org/source will redirect to github
* git.openssl.org is also shut down (the git repo is on github)
This commit just changes over to using openss.org/source instead of ftp.openssl.org. We might also need to switch to downloading directly from Github... let's see.
It also changes to cloning the head of openssl from github too.
> Don't download OpenSSL from ftp.openssl.org anyomre

- ext/openssl/ossl_pkcs12.c
- test/openssl/test_pkcs12.rb
This test was accidentally passing the value 2048 into the keytype parameter of PKCS12_create, not the mac_iter parameter (because it had one too many `nil`s in the call). This value is invalid, and will make OpenSSL perform an out-of-bounds read which is caught when compiling with ASAN.
This commit fixes the tests, and also adds some validation to PKCS12.create to make sure any keytype passed is actually valid. Since there only two valid keytype constants, and the whole feature is an export-grade crypto era thing only ever supported by old MSIE, it seems far more likely that code in the wild is using keytype similarly by mistake rather than as intended. So this validation might catch that.
> Fix test_create_with_mac_iter accidently setting keytype not maciter

- ext/openssl/extconf.rb
- ext/openssl/ossl_x509cert.c
- test/openssl/test_x509cert.rb
Ref https://github.com/ruby/openssl/issues/519
This makes verifying embedded certificate transparency signatures significantly easier, as otherwise the alternative was manipulating the ASN1 sequence, as in https://github.com/segiddins/sigstore-cosign-verify/pull/2/commits/656d992fa816613fd9936f53ce30972c2f2f4957
> Add X509::Certificate#tbs_bytes

- .github/workflows/github-pages.yml
This PR avoids an extra invocation of bundle install.
The only place this was used like this was in https://github.com/ruby/openssl/pull/764/files
> CI: Rely on setup-ruby to install Bundler gems

- ext/openssl/ossl_asn1.c
- ext/openssl/ossl_asn1.h
- lib/openssl.rb
- lib/openssl/asn1.rb
This is an initial proposal towards the goal of having as much of the lib in ruby as possible. While most of the code must be in C, some of the code in C is essentially calling back to ruby, and writing "ruby in C", if that makes any sense.
Lemme know what you think. I understand there may also be some cognitive load from jumping from C to ruby and back, so there's certainly a trade-off.
> rewriting most of the asn1 init code in ruby

- lib/openssl/buffering.rb
- test/openssl/test_pair.rb
- test/openssl/test_ssl.rb
- test/openssl/ut_eof.rb
Companion to getbyte but raise EOFError
Similar to https://github.com/ruby/openssl/pull/438
> Add SSLSocket#readbyte

- .github/workflows/test.yml
This PR is a temporary workaround for one of the 2 issues reported on the issue ticket https://github.com/ruby/openssl/issues/778 . I think we want to keep the CI as green as much as possible without down time. Let's apply this workaround. We can revert this commit later when I confirmed the OpenSSL site issue is fixed.
The `https://openssl.org/source/${{ matrix.openssl }}.tar.gz` links are not available right now.
See https://github.com/openssl/openssl/discussions/24984 for details.
I checked this PR on my forked repository in advance. The openssl-head fips case's failiure is another issue.
https://github.com/junaruga/ruby-openssl/actions/runs/10077294504/job/27859497255
> A temporary workaround to download OpenSSL archive files.

- ext/openssl/ossl_asn1.c
- ext/openssl/ossl_asn1.h
- ext/openssl/ossl_x509attr.c
- test/openssl/test_x509attr.rb
OpenSSL::ASN1 is being rewritten in Ruby. To make it easier, let's remove dependency to the instance variables and the internal-use function ossl_asn1_get_asn1type() outside OpenSSL::ASN1.
This also fixes the insufficient validation of the passed value with its tagging.
> x509attr: avoid using OpenSSL::ASN1 internals in #value=

- ext/openssl/extconf.rb
- ext/openssl/ossl_x509store.c
Instead of an ivar, so other ossl functions that take a store (such as `OpenSSL::Timestamp::Response#verify`) will use the correct time when verifying
> Set time directly on the x509 store

- .github/workflows/test.yml
I was told that OpenSSL project resolved the website issue at <https://github.com/openssl/openssl/discussions/24984#discussioncomment-10139652>.
This reverts commit f2c7729c4f56f7c7cc3f22d8b597fb78d06326bd.
I checked this reverting commit worked on the CI in my forked repository.
https://github.com/junaruga/ruby-openssl/actions/runs/10080561249
> Revert "A temporary workaround to download OpenSSL archive files."

- .github/workflows/test.yml
This PR is to upgrade OpenSSL and LibreSSL versions.
Note the OpenSSL projcect's website was changed with new structure, I change the URL to check the source archive files.
The way to go to the downloading page is below.
1. Click https://www.openssl.org
2. Click OpenSSL project icon
3. Click "Downloads" link on the top menu.
> CI: Upgrade OpenSSL and LibreSSL versions

- Rakefile
This PR is to make "rake debug" enhance, on the way suggested at https://github.com/ruby/openssl/pull/780#issuecomment-2250383833. I didn't need to take the `rake debug` out from `Rakefile`. Because the ruby code is executed in the child process by the `ruby %Q(-I./lib -ropenssl.so -ve'#{ruby_code}')` in the `Rakefile`.
---
We experienced a FIPS case specific Ruby OpenSSL error in the loading process of Ruby OpenSSL by calling the `ruby -ropenssl` (`require 'openssl'`) built with OpenSSL master branch which includes the commit <https://github.com/openssl/openssl/commit/6d47e819f2101f0219ddee67e855701e7bc3a716> but doesn't include the commit <https://github.com/openssl/openssl/commit/3c6e11495975a4eda4cc5886080afed6203711ac> fixing the issue.
The following error happened at …
> Make "rake debug" protective for a Ruby OpenSSL loading error.

- test/openssl/test_pkey.rb
This PR fixes the "openssl-master with fips provider" specific failure https://github.com/ruby/openssl/issues/785 in CI.
---
DSA kengen is not FIPS-approved. The `EVP_PKEY_paramgen` in the `OpenSSL::PKey.generate_parameters("DSA")` raises a DSA error in FIPS by the following commit.
https://github.com/openssl/openssl/commit/49a35f0#diff-605396c063194975af8ce31399d42690ab18186b422fb5012101cc9132660fe1R611-R614
> test_s_generate_parameters: Consider a DSA error in FIPS.

- test/openssl/test_pkey.rb
This PR fixes https://github.com/ruby/openssl/issues/787.
---
This commit fixes the following failure on OpenSSL master FIPS case.
```
1) Failure: test_ed25519_not_approved_on_fips(OpenSSL::TestPKey): OpenSSL::PKey::PKeyError expected but nothing was raised.
/home/runner/work/openssl/openssl/vendor/bundle/ruby/3.0.0/gems/test-unit-ruby-core-1.0.6/lib/core_assertions.rb:462:in `assert_raise'
/home/runner/work/openssl/openssl/test/openssl/test_pkey.rb:174:in `test_ed25519_not_approved_on_fips'
171:     MC4CAQAwBQYDK2VwBCIEIEzNCJso/5banbbDRuwRTg9bijGfNaumJNqM9u1PuKb7
172:     -----END PRIVATE KEY-----
173:     EOF
=> 174:     assert_raise(OpenSSL::PKey::PKeyError) do
175:       OpenSSL::PKey.read(priv_pem)
176:     end
177:   end
```
Because FIPS compliance is a continually moving target. …
> Remove test_ed25519_not_approved_on_fips.

- ext/openssl/ossl_asn1.c
- test/openssl/test_asn1.rb
Compare by the dotted decimal notation rather than the NID.
OpenSSL::ASN1::ObjectId can store OIDs that are not registered in OpenSSL's internal table. NID is not defined for such an OID, but it is not an error.
The == method also should not raise TypeError if the other object is not an instance of OpenSSL::ASN1::ObjectId.
Fixes: https://github.com/ruby/openssl/issues/791
> asn1: fix ObjectId#==

- Rakefile
- test/openssl/test_provider.rb
This PR is to fix the `test/openssl/test_provider.rb` in FIPS cases.
There are 2 commits. The 1st commit is the same with the PR https://github.com/ruby/openssl/pull/790. The 1st commit is a temporary workaround. I expect the PR #790 will be merged soon first before this PR is reviewed. The 2nd commit is the main commit for this PR.
> Fix test_provider.rb in FIPS.

- .github/workflows/test.yml
This PR is to upgrade used OpenSSL version to the latest ones according to the <https://openssl-library.org/source/>. There are no new LibreSSL versions according to the <http://www.libressl.org/releases.html>.
> CI: Upgrade OpenSSL versions

- Gemfile
This PR removes the warning message because prime Libraly will be the default gem.
```
ruby/openssl/test/openssl/test_bn.rb:266: warning: prime was loaded from the standard library, but is not part of the default gems since Ruby 3.1.0. Add prime to your Gemfile or gemspec.
```
> Add prime gem to d dependency

- ext/openssl/ossl_config.c
`OpenSSL::Config#[]=` is used in `OpenSSL::Config#to_s` example, 
https://github.com/ruby/openssl/blob/8367b16642f3a325d2344df6d9bcff6dd4f11393/ext/openssl/ossl_config.c#L308-L313
even though it was removed by #342 .
> Other two methods are removed because the corresponding functions
> disappeared in OpenSSL 1.1.0.
>
> - OpenSSL::Config#add_value
> - OpenSSL::Config#[]=
```ruby
irb(main):001> RUBY_VERSION
=> "3.3.5"
irb(main):002> OpenSSL::VERSION
=> "3.2.0"
irb(main):003> OpenSSL::OPENSSL_VERSION
=> "OpenSSL 3.0.2 15 Mar 2022"
irb(main):004> config = OpenSSL::Config.new
=> #<OpenSSL::Config sections=[]>
irb(main):005> config['default'] = {"foo"=>"bar","baz"=>"buz"}
(irb):5:in `<main>': undefined method `[]=' for an instance of OpenSSL::Config (NoMethodError)
```
> [DOC] Replace removed method in example for OpenSSL::Config#to_s

- lib/openssl/x509.rb
- test/openssl/test_x509cert.rb
The implementation of OpenSSL::X509::Certificate#crl_uris makes the assumption that each DistributionPoint in the CRL distribution points extension contains a single general name of type URI. This is not guaranteed by RFC 5280. A DistributionPoint may only contains something other than a URI, or more than one URI.
Let's include all URIs seen in the extension. If only non-URI pointers are found, return an empty array.
Fixes: https://github.com/ruby/openssl/issues/775
> x509: fix handling of multiple URIs in Certificate#crl_uris

- ext/openssl/ossl_pkcs7.c
- test/openssl/test_pkcs7.rb
Fixes the bug reported at https://github.com/ruby/ruby/pull/11515 in a different way. Defaulting to 40-bit RC2 doesn't seem right to me in the first place.
---
Require that users explicitly specify the desired algorithm. In my opinion, we are not in a position to specify the default cipher.
When OpenSSL::PKCS7.encrypt is given only two arguments, it uses "RC2-40-CBC" as the symmetric cipher algorithm. 40-bit RC2 is a US export-grade cipher and considered insecure.
Although this is technically a breaking change, the impact should be minimal. Even when OpenSSL is compiled with RC2 support and the macro OPENSSL_NO_RC2 is not defined, it will not actually work on modern systems because RC2 is part of the legacy provider.
> pkcs7: remove default cipher from PKCS7.encrypt

- ext/openssl/ossl.h
- ext/openssl/ossl_bn.c
as requested [here](https://github.com/ruby/openssl/pull/808#issuecomment-2444193790)
> move ractor safe macro to ossl.h

- ext/openssl/ossl_bn.c
- test/openssl/test_bn.rb
added frozen check on every state change.
> make bn shareable when frozen

- ext/openssl/ossl_x509crl.c
- ext/openssl/ossl_x509req.c
- test/openssl/test_pkey.rb
- test/openssl/test_x509cert.rb
- test/openssl/test_x509crl.rb
- test/openssl/test_x509req.rb
Allow requests and CRLs to be signed using Ed25519 private keys by passing a nil digest. This is similar to commit b0fc100091207d7eab20a349433ccbd8260c6ddd when signing certs.
Note Ed25519 keys do not implement the same `public_key` method, so the test must special case RSA and DSA.
> Support signing requests and CRLs using ED25519

- ext/openssl/ossl_ssl.c
ssl_servername_cb() is a callback function called from OpenSSL and Ruby exceptions must not be raised from it. Allocate the Array within rb_protect().
> ssl: fix potential exception in servername_cb

- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl_session.rb
Check the ID_callback_state ivar after SSL_read() or SSL_write() returns, similar to what ossl_start_ssl() does.
Previously, callbacks that can raise a Ruby exception were only called from ossl_start_ssl(). This has changed in OpenSSL 1.1.1. Particularly, the session_new_cb will be called whenever a client receives a NewSessionTicket message, which can happen at any time during a TLS 1.3 connection.
> ssl: handle callback exceptions in SSLSocket#sysread and #syswrite

- ext/openssl/ossl_config.c
- test/openssl/test_config.rb
should probably be initialized as frozen, given no state modifications
> ossl config: shareable when frozen

- ext/openssl/ossl_ssl.c
- lib/openssl/ssl.rb
- test/openssl/test_ssl.rb
Respect the SSL options set by default by `SSL_CTX()` or by the system-wide OpenSSL configuration file.
`OpenSSL::SSL::SSLContext#initialize` currently adds `OpenSSL::SSL::OP_ALL` on top of the default SSL options. Let's stop doing it.
`OpenSSL::SSL::OP_ALL` is a set of options that changes OpenSSL's behavior to workaround various TLS implementation bugs. Using it is considered usually safe, but is not completely harmless.
---
Also:
**ssl: do not clear existing SSL options in `SSLContext#set_params`**
Apply SSL options set in `DEFAULT_PARAMS `without clearing existing options, which may be set by a system-wide configuration file.
With a fresh installation of OpenSSL 3.3.1, this change will enable the `OpenSSL::SSL::OP_ENABLE_MIDDLEBOX_COMPAT` option for users of `SSLContext#set_params`. …
> ssl: do not enable OpenSSL::SSL::OP_ALL by default

- ext/openssl/ossl_cipher.c
- ext/openssl/ossl_digest.c
- test/openssl/test_cipher.rb
OpenSSL::Cipher#update accepts a String as the second argument to be used as the output buffer. The buffer must be directly writable, in other words, it must not be frozen and not a shared string.
rb_str_resize() does not make the String independent if the String already has the intended length. Use the rb_str_modify() family instead to check it.
Fixes: https://bugs.ruby-lang.org/issues/20937
> cipher: make output buffer String independent

- .github/workflows/push_gem.yml
Added .github/workflows/push_gem.yml based on that of net-imap and psych.
If nothing goes wrong, pushing a tag named v* should publish openssl-*.gem and openssl-*-java.gem to rubygems.org, and create a draft GitHub release.
See also: https://github.com/ruby/net-imap/pull/265
This is not tested yet.
> Configure RubyGems Trusted Publishing

- ext/openssl/ossl_pkcs12.c
- test/openssl/test_pkcs12.rb
Add a binding for PKCS12_set_mac() to set MAC parameters and (re-)calculate MAC for the content.
This allows generating PKCS#12 with consistent MAC parameters with different OpenSSL versions. OpenSSL 3.0 changed the default hash function used for HMAC and the KDF from SHA-1 to SHA-256.
Fixes: https://github.com/ruby/openssl/issues/772
> pkcs12: add PKCS12#set_mac

- ext/openssl/ossl_digest.c
OpenSSL::Digest#finish overrides Digest::Instance#finish and is called from the Digest::Class framework in the digest library. This method is not supposed to take any arguments, as suggested by the RDoc comment for Digest::Instance#finish.
It is a private method and not exposed to users. Let's remove it.
This optional parameter has been there since r15602 in Ruby trunk, which converted OpenSSL::Digest to the current state, a subclass of Digest::Class.
> digest: remove optional parameter from OpenSSL::Digest#finish 

- test/openssl/test_ssl_session.rb
In the test case, the client raises an exception in the session_new_cb and may not cleanly close the connection. Let's ignore exceptions raised at the server side.
Fixes: https://github.com/ruby/openssl/issues/828
> ssl: fix flaky test case test_ctx_client_session_cb_tls13_exception

- test/openssl/test_pkey_rsa.rb
In the `test_private_encoding_encrypted` test, we have a rsa private key pem file that was generated with `certtool`. I'm not entirely sure if the command that was used to generated the file was correct though. Dumping out the ASN.1 contents of this file indicates that this file was generated with an additional `--pkcs-cipher=aes-128`. When I try running the same command as the documentation indicates, the pem file would be encrypted with the default `3des-pkcs12` instead.
* Note: ASN.1 contents were dumped out with [der-ascii](https://github.com/google/der-ascii) and running `der2ascii -pem -i rsa.pem  > rsa.txt`.
The commentary above is fairly minor. The larger issue is that certtool's generated pkcs8 files aren't entirely consistent with [RFC8018 Appendix …
> pkey: Use openssl generated pkcs8 key instead

- ext/openssl/ossl_ssl.c
- lib/openssl/buffering.rb
- test/openssl/test_buffering.rb
[[Bug #20972]](https://bugs.ruby-lang.org/issues/20972)
The `rb_str_new_freeze` was added in https://github.com/ruby/openssl/issues/452 to better handle concurrent use of a Socket, but SSL sockets can't be used concurrently AFAIK, so we might as well just error cleanly.
By using `rb_str_locktmp` we can ensure attempts at concurrent write will raise an error, be we avoid causing a copy of the bytes.
We also use the newer `String#append_as_bytes` method when available to save on some more copies.
> Reduce OpenSSL::Buffering#do_write overhead

- .github/workflows/test.yml
- ext/openssl/extconf.rb
- ext/openssl/ossl.c
- ext/openssl/ossl_engine.c
- ext/openssl/ossl_kdf.c
- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_ssl.c
- ext/openssl/ossl_x509cert.c
- ext/openssl/ossl_x509store.c
- test/openssl/test_pkey.rb
- test/openssl/test_ssl.rb
- test/openssl/test_ssl_session.rb
- test/openssl/test_x509cert.rb
- test/openssl/test_x509crl.rb
- test/openssl/test_x509req.rb
- test/openssl/test_x509store.rb
> Require LibreSSL 3.9 or later (Drop support for 3.1-3.8)

- .github/workflows/test.yml
- ext/openssl/extconf.rb
- ext/openssl/ossl_hmac.c
- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_rand.c
- ext/openssl/ossl_ssl.c
- ext/openssl/ossl_x509.c
- ext/openssl/ossl_x509store.c
- test/openssl/test_pkey.rb
- test/openssl/test_pkey_dh.rb
- test/openssl/test_ssl.rb
- test/openssl/test_ssl_session.rb
- test/openssl/test_x509cert.rb
- test/openssl/test_x509crl.rb
- test/openssl/test_x509req.rb
- test/openssl/utils.rb
> Require OpenSSL 1.1.1 or later (Drop support for 1.1.0)

- ext/openssl/ossl_ts.c
- ext/openssl/ossl_x509cert.c
- ext/openssl/ossl_x509crl.c
- ext/openssl/ossl_x509req.c
While the struct is currently still public in OpenSSL, there has been an accessor since OpenSSL 0.9.8h. It would be nice if this accessor could be used so that the struct can be made opaque at some point in the future.
> Use X509_ALGOR_get0() accessor for X509_ALGOR

- ext/openssl/ossl_pkey_dh.c
- ext/openssl/ossl_pkey_dsa.c
- ext/openssl/ossl_pkey_rsa.c
- lib/openssl/pkey.rb
- test/openssl/test_pkey_dh.rb
- test/openssl/test_pkey_dsa.rb
- test/openssl/test_pkey_rsa.rb
The returned Hash from these methods contain 0 in place of a missing parameter in the key, for example:
pkey = OpenSSL::PKey.read(OpenSSL::PKey::RSA.new(2048).public_to_pem)
pp pkey.params
#=>
Let's use nil instead, which is more appropriate for indicating a missing value.
---
Also:
**pkey: implement PKey::{RSA,DSA,DH}#params in Ruby**
Move the definitions to lib/openssl/pkey.rb.
They don't have to be implemented in the native extension and can be simplified by using existing methods.
> pkey: change PKey::{RSA,DSA,DH}#params to use nil for missing parameters

- ext/openssl/extconf.rb
- ext/openssl/openssl_missing.h
- ext/openssl/ossl_ts.c
TS_VERIFY_CTX_set_certs() and TS_VERIFY_CTX_set_store() are deprecated in OpenSSL 3.4 in favor of the new functions with "set0" in the names.
Increment the reference counter of X509_STORE before setting it to TS_VERIFY_CTX. We avoided doing this to work around a bug that was present in OpenSSL < 1.0.2, fixed by openssl/openssl@bff9ce4db38b.
Fixes #837
> ts: use TS_VERIFY_CTX_set0_{store,certs}() on OpenSSL 3.4

- ext/openssl/ossl_pkey.c
- test/openssl/test_pkey_dsa.rb
Call ossl_pkey_check_public_key() to ensure that EVP_PKEY_missing_parameters() passes. This check should be cheap.
DSA#{to_der,to_pem,export,to_s} and PKey#{public_to_der,public_to_pem} cause a segfault if the receiver is an empty DSA instance with no parameters set.
Fixes <https://github.com/ruby/openssl/issues/845>.
> pkey: avoid calling i2d_PUBKEY family on an incomplete key

- test/openssl/test_ossl.rb
I'm not sure why https://github.com/ruby/openssl/commit/b0acc1a48eec67cf3837c466e7a6abb043c5150a is available on HEAD.
I removed that again.
> Removed needless workaround again

- ext/openssl/ossl_ssl.c
- lib/openssl/ssl.rb
- test/openssl/test_ssl.rb
Make these methods simple wrappers around SSL_CTX_set_{min,max}_proto_version().
When we introduced these methods in commit 18603949d316 (#142), which went to v2.1.0, we added a private method to SSLContext that set both the minimum and maximum protocol versions at the same time. This was to allow emulating the behavior using SSL options on older OpenSSL versions that lack SSL_CTX_set_{min,max}_proto_version(). Since we no longer support OpenSSL 1.0.2, the related code has already been removed.
In OpenSSL 1.1.1 or later, setting the minimum or maximum version to 0 is not equivalent to leaving it unset. Similar to SSL options, which we avoid overwriting as of commit 00bec0d905d5 and commit 77c3db2d6587 (#767), a system-wide configuration file may define a default protocol version bounds. …
> ssl: separate SSLContext#min_version= and #max_version=

- ext/openssl/ossl_pkey_ec.c
- test/openssl/test_pkey_ec.rb
The method has two forms, each corresponding to EC_POINT_mul() and EC_POINTs_mul(). The latter form does not work with any OpenSSL or LibreSSL versions that are still supported by upstream.
The latter form has an extremely confusing behavior, too, and using it would print a deprecation warning since commit 812de4253d25 in 2020, which went to 3.0.0. Let's remove it.
Related: #372 (added the deprecation warning)
> pkey/ec: remove deprecated PKey::EC::Point#mul(ary, ary [, bn]) form

- test/openssl/test_ssl.rb
This PR is adding a test for the https://github.com/ruby/openssl/pull/710 to ensure system wide setting MinProtocol is respected.
The test logic is similar with the https://github.com/ruby/openssl/pull/710#issuecomment-1880850890. On the `MinProtocol = TLSv1.3`, it is testing that the client should fail to connect to TLS 1.2 server, and should succeed to connect to TLS 1.3 server.
What do you think?
> test_ssl.rb: Test respecting system default min.

- test/openssl/test_ssl.rb
- test/openssl/test_ssl_session.rb
- test/openssl/utils.rb
This PR contains several mostly-unrelated small improvements in the test code for `OpenSSL::SSL`.
---
**ssl: remove start_immediately kwarg from test helper start_server**
The keyword argument is no longer used by any test cases.
---
**ssl: remove start_server_version from tests**
Use start_server instead of start_server_version.
start_server_version is a wrapper around start_server that forces the
server to a specific protocol version using the now-deprecated method
SSLSocket#ssl_version=, but it does more than that. The slightly
different method signature and default values are confusing. Let's
use start_server directly.
---
**ssl: fix test case test_npn_advertised_protocol_too_long**
The list of NPN protocols is validated in SSLContext#setup.
The assert_handshake_error is misleading. …
> Cleanups in SSL tests

- .github/workflows/test.yml
- ext/openssl/ossl.c
- ext/openssl/ossl_pkcs12.c
- ext/openssl/ossl_pkey_ec.c
- ext/openssl/ossl_ssl.c
- test/openssl/utils.rb
Follow up from https://github.com/ruby/openssl/issues/833
This contribution is to add basic build support for AWS-LC in the ruby/openssl gem. These changes represent the build portion of [a larger patch](https://github.com/aws/aws-lc/tree/main/tests/ci/integration/ruby_patch) in the AWS-LC's Ruby integration CI.
1. I've split the patch up to make it easier to digest, but that forces my hand to turn off testing in the AWS-LC CI for the time being. However, do let me know if you would prefer to review the tests adjustments in the same PR and I can remove the temporary CI workaround :).
2. AWS-LC has a few no-op functions and we use the `-Wdeprecated-declarations` to alert the consuming application of these. I've leveraged the `skip-warnings` CI option so that the build doesn't fail.
1. …
> Add build support for AWS-LC

- ext/openssl/ossl.c
- ext/openssl/ossl_pkcs7.c
- ext/openssl/ossl_ssl.c
- ext/openssl/ossl_x509cert.c
- ext/openssl/ossl_x509crl.c
- ext/openssl/ossl_x509name.c
- ext/openssl/ossl_x509revoked.c
- test/openssl/test_pkcs7.rb
Use explicit NULL checks before interacting with `STACK_OF(*)`. `ossl_*_sk2ary()` must no longer be called with NULL.
Checks for when `sk_*_num()` returns a negative number are removed. This can only happen when the stack is NULL.
This PR also cleans up unreachable code involving NULL stacks:
---
**pkcs7: add a test case for the data content type**
While it is not useful alone, it is still a valid content type. Some
methods on OpenSSL::PKCS7 are only meant to work with the signed-data or
enveloped-data. Add some assertions for their behavior with unsupported
content types. The next patches will update the relevant code.
---
**x509: do not check for negative return from X509_*_get_ext_count()**
These functions are wrappers of X509v3_get_ext_count(). The
implementation can never return a …
> Avoid calling sk_*() with NULL

- test/openssl/test_ssl.rb
- test/openssl/utils.rb
OpenSSL::SSL::SSLContext#cert_store= uses SSL_CTX_set_cert_store(). The store is used for verifying peer certificates and for building certificate chains to be sent to the peer if there is no chain explicitly provided by SSLContext#extra_chain_cert=.
Do not specify it in the common test helper start_server, as most callers do not require either function. Instead, update individual test cases that use client certificates to explicitly specify it in ctx_proc. A more direct test case is added to verify the latter function.
> ssl: remove cert_store from start_server test helper

- .github/workflows/test.yml
- test/openssl/test_asn1.rb
- test/openssl/test_bn.rb
- test/openssl/test_config.rb
- test/openssl/test_fips.rb
- test/openssl/test_pkcs12.rb
- test/openssl/test_pkcs7.rb
- test/openssl/test_pkey_dh.rb
- test/openssl/test_pkey_dsa.rb
- test/openssl/test_pkey_ec.rb
- test/openssl/test_ssl.rb
- test/openssl/test_ssl_session.rb
- test/openssl/utils.rb
Second follow up from https://github.com/ruby/openssl/issues/833
This contribution should be the next and final phase for adding support for AWS-LC in the ruby/openssl gem. These changes represent the build portion of [a larger patch](https://github.com/aws/aws-lc/tree/main/tests/ci/integration/ruby_patch) in the AWS-LC's Ruby integration CI. With this change, all tests have been accounted for and reenabled in the CI.
I understand that this patch is a bit large, so I've broken everything up to into smaller documented commits that'll make things easier to digest. I've also tried following a similar commit messaging pattern that the maintainers use.
However, do feel free to let me know if I should make separate PR contributions for some of these or if there are any changes within the commit …
> Patch and enable tests with AWS-LC

- test/openssl/test_digest.rb
The `pend` are no longer necessary, as they work with all OpenSSL variants we currently support. They were added in OpenSSL 1.1.1 and LibreSSL 3.8.0. They are also supported by the current AWS-LC release.
This makes the SHA-3 tests run with AWS-LC correctly. AWS-LC does not report SHA-3 in `OpenSSL::Digest.digests`.
> digest: always run SHA-3 and truncated SHA-2 tests

- test/openssl/test_ssl.rb
As reported in <https://github.com/ruby/ruby/pull/12823>, check_supported_protocol_versions is unstable and occasionally fails with Errno::ECONNABORTED during SSLSocket#connect on Windows.
When the server-side SSLContext specifies an unsupported SSL/TLS protocol version, start_server accepts a TCP connection but closes it without reading ClientHello, as SSLSocket#accept immediately raises an exception. With Winsock, this can cause the client-side SSLSocket#connect to raise Errno::ECONNABORTED.
While the simplest fix is to add rescue Errno::ECONNABORTED, this method can be simplified. Instead, let's set up a server that accepts all protocol versions and test client connections with different settings.
> ssl: refactor check_supported_protocol_versions

- test/openssl/test_ssl.rb
Fixes https://github.com/ruby/openssl/pull/866
Commit aa7f03e18f26 broke `test_minmax_version` and `test_fallback_scsv` on systems using OpenSSL 1.1.1 with a system-wide configuration file that specifies `MinProtocol=TLSv1.2`.
http://rubyci.s3.amazonaws.com/debian11/ruby-master/log/20250228T003003Z.fail.html.gz
http://rubyci.s3.amazonaws.com/rhel8/ruby-master/log/20250228T003003Z.fail.html.gz
These test cases were already broken before the commit, but they were being skipped because `check_supported_protocol_versions` failed to detect TLS 1.1 support. To avoid affected by the configuration file, explicitly reset `SSLContext#min_version` when TLS 1.1 or older is required.
The test cases are also broken with OpenSSL 3.0 or later, but this is not currently visible because it still fails to …
> ssl: fix tests using TLS 1.1 or older

- .github/workflows/test.yml
- test/openssl/test_pkey_dh.rb
Cc: @samuel40791765
This PR is on top of another PR https://github.com/ruby/openssl/pull/862. So, please review the #862 first. Essentially 3 commits. This PR is to improve tests related to the AWS-LC non-FIPS case.
The 1st commit is to disable the cache for the AWS-LC case on CI. In the current logic of the cache key, we cannot enable the cache to get the latest version of the AWS-LC.
The 2nd commit is to specify the library directory as "lib" explicitly. The logic of compiling the AWS-LC is useful to see how to compile it. Because I saw the "lib64" directory was created without the `-DCMAKE_INSTALL_LIBDIR=lib` option on Fedora Linux 41.
The 3rd commit is to remove meaningless `aws_lc?`. As I mentioned at https://github.com/ruby/openssl/pull/860#issuecomment-2682643747, we can safely use …
> Improve AWS-LC tests

- ext/openssl/ossl_bn.c
- ext/openssl/ossl_cipher.c
- ext/openssl/ossl_digest.c
- ext/openssl/ossl_hmac.c
- ext/openssl/ossl_ocsp.c
- ext/openssl/ossl_pkcs12.c
- ext/openssl/ossl_pkcs7.c
- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_pkey_dh.c
- ext/openssl/ossl_pkey_dsa.c
- ext/openssl/ossl_pkey_ec.c
- ext/openssl/ossl_pkey_rsa.c
- ext/openssl/ossl_ssl_session.c
- ext/openssl/ossl_x509attr.c
- ext/openssl/ossl_x509cert.c
- ext/openssl/ossl_x509crl.c
- ext/openssl/ossl_x509ext.c
- ext/openssl/ossl_x509name.c
- ext/openssl/ossl_x509req.c
- ext/openssl/ossl_x509revoked.c
I wish there were these notes when I read the document.  
The functionality is useful, especially for `Digest` and `HMAC` stuff.
I hope more people notice this somewhat hidden functionality.
> Improve document of `initialize_copy`

- test/openssl/test_pkcs7.rb
Extension from this original thread regarding the PKCS7 test we skipped in AWS-LC: https://github.com/ruby/openssl/pull/855#discussion_r1954311654
We've been doing more investigations against the PKCS7 issue like we promised. It turns out @rhenium was right in that this was an issue with "decoding" indefinite BER rather than "encoding". `ASN1_TFLG_NDEF` is in charge of encoding indefinite BER for PKCS7 in OpenSSL, but that's only used in the "PKCS7 streaming APIs" and is not used by default. The PKCS7 test file has indefinite BER within it, which AWS-LC was not properly decoding.
AWS-LC had been decoding the indefinite BER to an unusable output. Instead of allowing an invalid state to be parsed, we've decided to revert https://github.com/aws/aws-lc/commit/2a722260329a62e0682410060f84cf1449 …
> Skip PKCS7 with indefinite length test in AWS-LC

- test/openssl/test_pkcs7.rb
The test case `test_split_content` fails on RHEL 9 and Fedora 41 because their OpenSSL packages do not accept SHA-1 signatures. This was only caught after commit 69fd7f886313 added the missing assertion.
While the example PKCS#7 structures could be simply regenerated with SHA-256, this test case could be simplified because it is checking two different things.
Replace `test_split_content` with separate test cases: one verifying `signed-data` `authenticatedAttributes` and another for decoding BER input.
Fixes https://github.com/ruby/openssl/issues/875
> pkcs7: fix test failure on RHEL 9

- test/openssl/test_pkey_rsa.rb
Fedora OpenSSL 3.5 on rawhide stopped accepting SHA-1 PSS[1] parameters. This is different from the SHA-1 signatures which Fedora OpenSSL stopped accepting since Fedora 41.[2]
This commit fixes the following test failures related to the SHA-1 PSS parameters with Fedora OpenSSL 3.5.
Note these failures are the downstream Fedora OpenSSL RPM specific. The tests pass without this commit with the upstream OpenSSL 3.5. Though the test failures are Fedora rawhide (Fedora 43) specific right now, I want to contribute this fix to this project. Because Ruby project manages Fedora and RHEL servers.
I heard from a maintainer of the Fedora OpenSSL that the following patch `0018-RH-Allow-disabling-of-SHA1-signatures.patch` on the rawhide branch in the [Fedora OpenSSL (rpms/openssl) package …
> Fix the tests using SHA-1 Probabilistic Signature Scheme (PSS) parameters.

- ext/openssl/ossl_asn1.c
- test/openssl/test_asn1.rb
EOC octets are required at the end of contents of a constructed encoding that uses the indefinite length form. This cannot be assumed from the end of the input. Raise an exception when necessary.
> asn1: check for missing EOC in indefinite length encoding

- .github/workflows/test.yml
Changes include:
- Test against OpenSSL 3.5.0 and LibreSSL 4.1.0.
- Run "rake test" and "rake test_fips" in the same job so that we can
avoid compiling the same OpenSSL version twice.
- Use the "no-tests" option when compiling OpenSSL 3.0 or later. This
disables compiling OpenSSL's test suite which we do not run.
> .github/workflows/test.yml: update test-openssls

- test/openssl/test_pkcs7.rb
During the collaboration we did on https://github.com/ruby/openssl/pull/855, we promised that we'd be fixing our support for parsing indefinite BER and BER constructed strings in AWS-LC soon. As of [AWS-LC v1.50.0](https://github.com/aws/aws-lc/releases/tag/v1.50.0), we've added support for both issues.
This PR is to remove the pending test case regarding the missing feature. We appreciate the help with pinpointing this gap!
> AWS-LC has support for parsing ber constructed strings now

- .github/workflows/test.yml
'workflow_dispatch' is very helpful for forcing a CI run when either a dependency, Ruby, or the 'GHA Ruby system' (setup-ruby, etc)
have changed.
I created this commit in Nov-23, but forgot to create a PR...
> CI test.yml - add workflow_dispatch

- ext/openssl/extconf.rb
- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl.rb
Add methods for setting supported signature algorithms, corresponding to `SSL_CTX_set1_sigalgs_list()` and `SSL_CTX_set1_client_sigalgs_list()`, respectively.
Supersedes https://github.com/ruby/openssl/pull/769
/cc @mj-vivavis
> ssl: add SSLContext#sigalgs= and #client_sigalgs= 

- Rakefile
Restore the dependency accidentally removed by commit 77133c6fc2af.
> Rakefile: fix :test/:test_fips => :compile dependency

- ext/openssl/extconf.rb
- ext/openssl/ossl_ssl.c
- test/openssl/test_ssl.rb
@rhenium This PR is related to https://github.com/ruby/openssl/issues/894 - Add features to get the following data from a TLS client.
* Peer signing digest
* Peer signature type
* Negotiated TLS1.3 group
Note I added the `#include <openssl/obj_mac.h>` for `NID_undef` and `#include <openssl/objects.h>` for the `OBJ_nid2sn()`.
I am not sure about the best location where I should put these new logic, the functions and unit tests in the files. I would appreciate if you tell me the best location.
You can also just cherry-pick this PR or refer to this PR or create your new PR.
Could you review the PR? Thank you!
> ssl: add SSLSocket#sigalg, #peer_sigalg, #group

- ext/openssl/ossl_x509store.c
- test/openssl/test_x509store.rb
Commit ef277083ba76 overlooked a caller of ossl_x509_new() with NULL argument. OpenSSL::X509::StoreContext#current_cert may not have a certificate to return if StoreContext#verify has not been called.
> x509store: fix StoreContext#current_cert

- Rakefile
- ext/openssl/ossl_pkcs7.c
- test/openssl/test_pkcs7.rb
This includes:
- Update test keys and add omissions for enveloped-data tests so that the rest can be tested in the FIPS mode.
- Add tests for PKCS7#error_string and #data.
- Check more error paths.
- Various style fixes.
> pkcs7: clean up tests

- ext/openssl/ossl_pkcs7.c
- test/openssl/test_pkcs7.rb
Only call PKCS7_get_detached() if the PKCS7 object is a signed-data. This is only useful for the content type, and leaves an error entry if called on a PKCS7 object with a different content type.
> pkcs7: fix error queue leak in OpenSSL::PKCS7#detached

- ext/openssl/ossl_pkcs7.c
- test/openssl/test_pkcs7.rb
---
**pkcs7: refactor error handling in PKCS7#add_data**
Raise an exception right after an OpenSSL function returns an error. Checking `ERR_peek_error()` is not reliable way to see if an error has occurred or not, as OpenSSL functions do not always populate the error queue.
---
**pkcs7: make PKCS7#add_recipient actually useful**
Add a simple test case that creates an enveloped-data structure without using the shorthand method, and fix two issues preventing this from working correctly.
First, `OpenSSL::PKey::PKCS7#add_recipient` currently inserts an incomplete `PKCS7_RECIP_INFO` object into the `PKCS7` object. When duplicating an unfinalized `PKCS7_RECIP_INFO`, the internal `X509` reference must also be copied, as it is later used by `#add_data` to fill the rest.
A similar issue with …
> pkcs7: make PKCS7#add_recipient actually useful

- ext/openssl/ossl_x509store.c
Both the X509 store and X509 store context were missing write barriers. To the callback object being stored in the ex data.
These values were also being stored as an IV, however in Ruby HEAD we're now storing the IVs for T_DATA (generic IVs) on a separate object. So we need an additional write barrier if we're marking it from this object.
I believe this was always necessary, because we could have done incremental marking ahead of compaction, and without the write barrier the mark function could have been run before @verify_callback was assigned.
This was detected by [wbcheck](https://github.com/ruby/ruby/pull/13557)
> Add missing write barriers in X509

- CONTRIBUTING.md
I would like to add the Debugging section to explain about the `OpenSSL.debug = true` in the `CONTRIBUTING.md`. I see the option is effective to debug.
> CONTRIBUTING.md: Add Debugging section [ci skip]

- ext/openssl/ossl.h
- ext/openssl/ossl_pkey.c
- ext/openssl/ossl_pkey.h
- ext/openssl/ossl_pkey_dh.c
- ext/openssl/ossl_pkey_dsa.c
- ext/openssl/ossl_pkey_ec.c
- ext/openssl/ossl_pkey_rsa.c
- test/openssl/test_pkey_dh.rb
- test/openssl/test_pkey_dsa.rb
- test/openssl/test_pkey_ec.rb
- test/openssl/test_pkey_rsa.rb
When `OpenSSL::PKey::{DH,DSA,EC,RSA}.new` is called without any arguments, it sets up an empty corresponding low-level struct and wraps it in an `EVP_PKEY`. This form has been supported so that users can fill the fields later using low-level setter methods such as `OpenSSL::PKey::RSA#set_key`.
Such setter methods are not compatible with OpenSSL 3.0 or later, where pkeys are immutable once created. This means that the ability to create an empty instance is useless. Let's remove it and raise `ArgumentError` if attempted.
Related:
- https://github.com/ruby/openssl/pull/480
- https://github.com/ruby/openssl/issues/845
> pkey: disallow {DH,DSA,EC,RSA}.new without arguments on OpenSSL 3.0

- test/openssl/test_pkey_dh.rb
- Generate smaller parameters in `test_new_generate`. Generating 2048-bit parameters is slow and sometimes takes a few minutes on GitHub-hosted CI runners. Also test the `DH.generate` alias, not just `DH.new`.
- Simplify `test_new_break` to just check exceptions raised in the block because it is redundant.
- Remove unnecessary `OpenSSL::PKey::DH#public_key` calls.
- Update bare `assert` with more appropriate methods.
> pkey/dh: refactor tests
