openssl.gemspec
=> Compile extension on gem install.

ext/openssl/deprecation.rb, ext/openssl/extconf.rb, ext/openssl/ossl.c, ext/openssl/ossl.h, ext/openssl/ossl_bio.c, ext/openssl/ossl_cipher.c, ext/openssl/ossl_pkey_dsa.c, ext/openssl/ossl_rand.c, ext/openssl/ossl_ssl.c, ext/openssl/ossl_ssl.h, lib/openssl.rb, lib/openssl/bn.rb, lib/openssl/buffering.rb, lib/openssl/cipher.rb, lib/openssl/config.rb, lib/openssl/digest.rb, lib/openssl/pkey.rb, lib/openssl/ssl.rb, lib/openssl/x509.rb
picked from https://github.com/ruby/ruby HEAD
=> sync code from upstream

lib/openssl/pkey.rb, test/test_pkey_dh.rb
Added 2048 bit length for DH-key
=> Support 2048 bit length DH-key

CONTRIBUTING.md, README.md
I also think we should possibly document the `ruby-openssl-docker` project for those interested in building and testing, or contributing, to the development of OpenSSL!
=> Readme contrib docs

appveyor.yml
(This is work in progress status yet)
=> Enabled appveyor for Windows build

README.md
Added appveyor status by status badge
=> Appveyor status badge

History.md, openssl.gemspec
Updating History.md.
/cc @hsbt @zzak
=> Ruby/OpenSSL 2.1.0.beta1

test/test_pair.rb
When the previous SSLSocket#write_nonblock call does not finish writing
the complete contents, SSL_shutdown() which is called through
SSLSocket#close will not send a close_notify alert.
As of commit e3a305063675 ssl_pair no longer uses the sync_close
feature. Do not expect that SSL_read() gets ECONNRESET.
Reported at: https://github.com/ruby/ruby/commit/609103dbb5fb182eec12f052226c43e39b907682#commitcomment-24056418
@MSP-Greg I haven't been able to reproduce the hang myself, but I think this patch would fix the problem. Can you confirm this?
=> test/test_pair: fix test_write_nonblock{,_no_exceptions}

openssl.gemspec
Follow up https://bugs.ruby-lang.org/issues/13906
=> To use upstream url of github

History.md, ext/openssl/ossl_version.h, openssl.gemspec
Bump the version number, and update History.md.
=> Ruby/OpenSSL 2.0.6

History.md, appveyor.yml, ext/openssl/ossl_cipher.c, ext/openssl/ossl_ns_spki.c, ext/openssl/ossl_pkey.c, ext/openssl/ossl_pkey.h, ext/openssl/ossl_ssl.c, ext/openssl/ossl_x509cert.c, ext/openssl/ossl_x509crl.c, ext/openssl/ossl_x509req.c, openssl.gemspec, test/test_cipher.rb, test/test_ssl_session.rb
Merge maint and update History.md.
=> Ruby/OpenSSL 2.1.0.beta2

lib/openssl/ssl.rb, test/test_ssl.rb
Hi!
This PR is related to #225 .
* add `SSLSocket.open` as alias of `SSLSocket.new`
=> add `SSLSocket.open`

ext/openssl/ossl_kdf.c
Same as https://github.com/ruby/openssl/pull/284
=> Use fixed_length_secure_compare in HKDF example

lib/openssl/ssl.rb
=> Modify SSLServer#listen default argument value to Socket::SOMAXCONN

ext/openssl/ossl_ssl.c
=> Update renegotiation_cb docstring to reflect its actual behavior in MRI

.github/workflows/workflow.yml, test/test_asn1.rb, test/test_bn.rb, test/test_ssl.rb, test/test_x509name.rb, test/utils.rb
@mame @hsbt @nobu There is one issue in `test_sysread_nonblock_and_syswrite_nonblock_keywords` but I'm not sure how to fix it yet. Do you have any ideas?
=> Merge in changes to tests from ruby/test/openssl.

ext/openssl/extconf.rb, ext/openssl/ossl_engine.c
I'm guessing this may resolve #189 (testing still needed, still waiting on a response to the issue)
=> Add AWS CloudHSM engine

openssl.gemspec, test/test_ossl.rb, test/test_ts.rb
https://github.com/ruby/ruby is a different structure from ruby/openssl. I fixed some of code that is not working with it.
=> Support Ruby repository

ext/openssl/ossl_ssl.c, test/openssl/test_ssl.rb
Closes #291.
This PR includes the peer IP address in error messages when trying to connect to an SSL socket/server.
cc: @ioquatix
=> Include peer ip address in SSL start errors

.github/workflows/test.yml
=> Install openssl with vcpkg on mswin

ext/openssl/ossl.c
https://bugs.ruby-lang.org/issues/19584
=> Register global variables before assignment

.github/workflows/test.yml
This PR is to upgrade OpenSSL and LibreSSL versions.
=> CI: Upgrade OpenSSL and LibreSSL versions.

Rakefile
I executed the `rake test_fips` for all the test files, and checked the test files that already passed in the FIPS cases. Let's add the files to the `test_fips` task in the `Rakefile`.
=> Add passing test files in FIPS.
